//! Headless runtime (no Tauri): an axum HTTP/WebSocket server that
//! exposes the same business command surface the desktop build exposes
//! via `#[tauri::command]`. Compiled only when the `desktop` feature is
//! off (`--no-default-features`).
//!
//! Routes:
//!   GET  /health      -> { ok, version, mode }
//!   POST /api/invoke  -> { cmd, args } -> { ok, value | error }
//!   GET  /ws          -> WebSocket broadcast of frontend events
//!
//! The invoke dispatch below is AUTO-GENERATED by
//! /tmp/gen_headless.py — do not edit by hand.
#![cfg(not(feature = "desktop"))]

use std::sync::Arc;

use axum::extract::ws::{Message, WebSocket, WebSocketUpgrade};
use axum::extract::State as AxumState;
use axum::response::IntoResponse;
use axum::routing::{get, post};
use axum::{Json, Router};
use serde::de::DeserializeOwned;
use serde::Deserialize;
use serde_json::Value;
use tokio::sync::broadcast;

use crate::app_context::AppContext;
use crate::events::WsEventEmitter;
use crate::runtime::shell_runner::ShellRunRegistry;
use crate::services::proxy::ProxyServerState;

use crate::commands::chat_history::{ChatHistoryMessageRef, ChatHistorySearchArgs, ChatHistorySegmentMutationInput, ChatHistoryUpsertInput};
use crate::commands::mcp::{McpServerConfig};
use crate::commands::subagent_store::{SubagentIdentityListInput, SubagentIdentityUpsertInput, SubagentMessageAppendInput, SubagentMessageListInput, SubagentRunListInput, SubagentRunLoadInput, SubagentRunPruneInput, SubagentRunSaveInput};
use crate::commands::subagent_worktree::{SubagentWorktreeApplyInput, SubagentWorktreeCleanupInput, SubagentWorktreeCreateInput, SubagentWorktreeStatusInput};
use crate::commands::system::{SystemPastedTextInput, SystemUploadedReadableFileInput};
use crate::runtime::task_runner::{HttpRequestInput};
use crate::services::automation::{AutomationApplyInput, CompletePromptRunInput};
use crate::services::gateway::{GatewayChatQueueEventInput, GatewayChatQueueResponseInput};
use crate::services::gateway::chat_ingress::{GatewayChatCheckpointInput, GatewayChatIngressBatchInput};
use crate::services::memory::{MemoryAcceptArgs, MemoryBatchArgs, MemoryDeleteArgs, MemoryDeleteProjectArgs, MemoryListArgs, MemoryOrganizeDueClaimArgs, MemoryOrganizeRunCreateArgs, MemoryOrganizeRunListArgs, MemoryOrganizeRunReadArgs, MemoryOrganizeRunUpdateArgs, MemoryQuotaSummaryArgs, MemoryReadArgs, MemoryRecentRejectionsArgs, MemorySearchArgs, MemoryUpdateArgs, MemoryWriteArgs};
use crate::services::tunnel::{GatewayTunnelCreateInput, GatewayTunnelUpdateInput};

use std::collections::HashMap;

/// Shared headless state, mirroring the tauri `manage()` set of the
/// desktop build: the AppContext fields plus headless-only registries.
#[derive(Clone)]
pub struct HeadlessState {
    pub ctx: Arc<AppContext>,
    pub emitter: Arc<WsEventEmitter>,
    pub mcp_runtime: Arc<crate::commands::mcp::McpRuntimeManager>,
    pub shell_runs: Arc<ShellRunRegistry>,
    pub hook_scopes: Arc<crate::commands::hook::HookScopeRegistry>,
    pub proxy_server: Arc<ProxyServerState>,
}

/// Remove and deserialize a required argument by snake_case name.
fn take_arg<T: DeserializeOwned>(args: &mut Value, name: &str) -> Result<T, String> {
    let obj = args.as_object_mut().ok_or_else(|| "args must be a JSON object".to_string())?;
    let value = obj.remove(name).ok_or_else(|| format!("missing argument `{name}`"))?;
    serde_json::from_value(value).map_err(|e| format!("argument `{name}`: {e}"))
}

/// Remove and deserialize an optional argument; absent or null yields `None`.
fn take_arg_opt<T: DeserializeOwned>(args: &mut Value, name: &str) -> Result<Option<T>, String> {
    let obj = args.as_object_mut().ok_or_else(|| "args must be a JSON object".to_string())?;
    match obj.remove(name) {
        None | Some(Value::Null) => Ok(None),
        Some(value) => serde_json::from_value(value).map(Some)
            .map_err(|e| format!("argument `{name}`: {e}")),
    }
}

fn to_value<T: serde::Serialize>(v: T) -> Result<Value, String> {
    serde_json::to_value(v).map_err(|e| format!("serialize result: {e}"))
}

/// Dispatch a command invocation to the same business functions the desktop
/// adapters call. Async functions are awaited; sync ones run inline.
pub async fn dispatch(state: &HeadlessState, cmd: &str, args: Value) -> Result<Value, String> {
    let mut args = args;
    match cmd {
        // ===== app =====
    "app_window_pinned" => Err("desktop-only command: app_window_pinned".to_string()),
    "app_toggle_window_pin" => Err("desktop-only command: app_toggle_window_pin".to_string()),
    "app_set_global_shortcuts" => Err("desktop-only command: app_set_global_shortcuts".to_string()),
    "app_runtime_platform" => {
        to_value(crate::commands::app::app_runtime_platform())
    },
    "app_set_close_window_behavior" => {
        let behavior_v: String = take_arg(&mut args, "behavior")?;
        match crate::commands::app::app_set_close_window_behavior(behavior_v, &state.ctx.close_window_behavior) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "app_confirmed_exit" => Err("desktop-only command: app_confirmed_exit".to_string()),
    "app_macos_traffic_light_metrics" => Err("desktop-only command: app_macos_traffic_light_metrics".to_string()),
        // ===== tray =====
    "app_tray_menu_sync" => Err("desktop-only command: app_tray_menu_sync".to_string()),
        // ===== update =====
    "app_update_check" => Err("desktop-only command: app_update_check".to_string()),
    "app_update_install" => Err("desktop-only command: app_update_install".to_string()),
    "app_restart" => Err("desktop-only command: app_restart".to_string()),
        // ===== system =====
    "system_pick_folder" => Err("file picker is unavailable in headless mode".to_string()),
    "system_pick_file" => Err("file picker is unavailable in headless mode".to_string()),
    "system_create_project_folder" => {
        let parent_v: String = take_arg(&mut args, "parent")?;
        let name_v: String = take_arg(&mut args, "name")?;
        match crate::commands::system::system_create_project_folder(parent_v, name_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_pick_readable_files" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let max_files_v: Option<usize> = take_arg_opt(&mut args, "max_files")?;
        match crate::commands::system::system_pick_readable_files(workdir_v, max_files_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_import_readable_file_paths" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let paths_v: Vec<String> = take_arg(&mut args, "paths")?;
        let max_files_v: Option<usize> = take_arg_opt(&mut args, "max_files")?;
        match crate::commands::system::system_import_readable_file_paths(workdir_v, paths_v, max_files_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_import_uploaded_readable_files" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let files_v: Vec<SystemUploadedReadableFileInput> = take_arg(&mut args, "files")?;
        let max_files_v: Option<usize> = take_arg_opt(&mut args, "max_files")?;
        match crate::commands::system::system_import_uploaded_readable_files(workdir_v, files_v, max_files_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_import_pasted_texts" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let texts_v: Vec<SystemPastedTextInput> = take_arg(&mut args, "texts")?;
        match crate::commands::system::system_import_pasted_texts(workdir_v, texts_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_read_uploaded_image_preview" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let absolute_path_v: String = take_arg(&mut args, "absolute_path")?;
        match crate::commands::system::system_read_uploaded_image_preview(workdir_v, absolute_path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_read_uploaded_native_attachment" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let absolute_path_v: Option<String> = take_arg_opt(&mut args, "absolute_path")?;
        let kind_v: Option<String> = take_arg_opt(&mut args, "kind")?;
        match crate::commands::system::system_read_uploaded_native_attachment(workdir_v, absolute_path_v, kind_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_list_skill_files" => {
        match crate::commands::system::system_list_skill_files().await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_ensure_builtin_skills" => {
        match crate::commands::system::system_ensure_builtin_skills().await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_manage_skill" => {
        let payload_v: Value = take_arg(&mut args, "payload")?;
        match crate::commands::system::system_manage_skill(payload_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_read_skill_text" => {
        let path_v: String = take_arg(&mut args, "path")?;
        let offset_v: Option<usize> = take_arg_opt(&mut args, "offset")?;
        let length_v: Option<usize> = take_arg_opt(&mut args, "length")?;
        match crate::commands::system::system_read_skill_text(path_v, offset_v, length_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_read_skill_metadata" => {
        let path_v: String = take_arg(&mut args, "path")?;
        match crate::commands::system::system_read_skill_metadata(path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_append_debug_jsonl" => {
        let conversation_id_v: String = take_arg(&mut args, "conversation_id")?;
        let entry_v: Value = take_arg(&mut args, "entry")?;
        match crate::commands::system::system_append_debug_jsonl(conversation_id_v, entry_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_clipboard_read_text" => {
        match crate::commands::system::system_clipboard_read_text().await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_begin_power_activity" => {
        let activity_id_v: String = take_arg(&mut args, "activity_id")?;
        let reason_v: String = take_arg(&mut args, "reason")?;
        let ttl_ms_v: Option<u64> = take_arg_opt(&mut args, "ttl_ms")?;
        match crate::commands::system::system_begin_power_activity(activity_id_v, reason_v, ttl_ms_v, &state.ctx.power_activity) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "system_end_power_activity" => {
        let activity_id_v: String = take_arg(&mut args, "activity_id")?;
        match crate::commands::system::system_end_power_activity(activity_id_v, &state.ctx.power_activity) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== cron =====
    "cron_validate_expression" => {
        let expression_v: String = take_arg(&mut args, "expression")?;
        match crate::commands::cron::cron_validate_expression(expression_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "automation_snapshot" => {
        match crate::commands::cron::automation_snapshot(&state.ctx.automation_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "automation_cron_apply" => {
        let input_v: AutomationApplyInput = take_arg(&mut args, "input")?;
        match crate::commands::cron::automation_cron_apply(input_v, &state.ctx.automation_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "automation_hooks_apply" => {
        let input_v: AutomationApplyInput = take_arg(&mut args, "input")?;
        match crate::commands::cron::automation_hooks_apply(input_v, &state.ctx.automation_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "automation_list_runs" => {
        let task_id_v: String = take_arg(&mut args, "task_id")?;
        let limit_v: Option<usize> = take_arg_opt(&mut args, "limit")?;
        match crate::commands::cron::automation_list_runs(task_id_v, limit_v, &state.ctx.automation_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "automation_clear_runs" => {
        let task_id_v: String = take_arg(&mut args, "task_id")?;
        match crate::commands::cron::automation_clear_runs(task_id_v, &state.ctx.automation_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "automation_run_cron_now" => {
        let task_id_v: String = take_arg(&mut args, "task_id")?;
        match crate::commands::cron::automation_run_cron_now(task_id_v, &state.ctx.automation_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "automation_claim_prompt_runs" => {
        match crate::commands::cron::automation_claim_prompt_runs(&state.ctx.automation_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "automation_release_prompt_run" => {
        let execution_id_v: String = take_arg(&mut args, "execution_id")?;
        match crate::commands::cron::automation_release_prompt_run(execution_id_v, &state.ctx.automation_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "automation_complete_prompt_run" => {
        let input_v: CompletePromptRunInput = take_arg(&mut args, "input")?;
        match crate::commands::cron::automation_complete_prompt_run(input_v, &state.ctx.automation_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== hook =====
    "hook_run_script" => {
        let workdir_v: Option<String> = take_arg_opt(&mut args, "workdir")?;
        let script_v: String = take_arg(&mut args, "script")?;
        let timeout_ms_v: Option<u64> = take_arg_opt(&mut args, "timeout_ms")?;
        let scope_id_v: Option<String> = take_arg_opt(&mut args, "scope_id")?;
        let context_v: Option<HashMap<String, String>> = take_arg_opt(&mut args, "context")?;
        match crate::commands::hook::hook_run_script(workdir_v, script_v, timeout_ms_v, scope_id_v, context_v, &state.hook_scopes).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "hook_run_http_requests" => {
        let requests_v: Vec<HttpRequestInput> = take_arg(&mut args, "requests")?;
        let scope_id_v: Option<String> = take_arg_opt(&mut args, "scope_id")?;
        match crate::commands::hook::hook_run_http_requests(requests_v, scope_id_v, &state.hook_scopes).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "hook_cancel_scope" => {
        let scope_id_v: String = take_arg(&mut args, "scope_id")?;
        match crate::commands::hook::hook_cancel_scope(scope_id_v, &state.hook_scopes).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== settings =====
    "settings_list_ccswitch_providers" => {
        match crate::commands::settings::settings_list_ccswitch_providers().await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_list_cherry_studio_providers" => {
        match crate::commands::settings::settings_list_cherry_studio_providers().await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_list_cherry_studio_providers_from_path" => {
        let data_path_v: String = take_arg(&mut args, "data_path")?;
        match crate::commands::settings::settings_list_cherry_studio_providers_from_path(data_path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_load_all" => {
        match crate::commands::settings::settings_load_all().await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_save_providers" => {
        let payload_v: Value = take_arg(&mut args, "payload")?;
        match crate::commands::settings::settings_save_providers(payload_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_save_system" => {
        let payload_v: Value = take_arg(&mut args, "payload")?;
        match crate::commands::settings::settings_save_system(payload_v, &state.ctx.automation_scheduler).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_save_mcp" => {
        let payload_v: Value = take_arg(&mut args, "payload")?;
        match crate::commands::settings::settings_save_mcp(payload_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_save_remote" => {
        let payload_v: Value = take_arg(&mut args, "payload")?;
        match crate::commands::settings::settings_save_remote(payload_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_save_memory" => {
        let payload_v: Value = take_arg(&mut args, "payload")?;
        match crate::commands::settings::settings_save_memory(payload_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_save_agents" => {
        let payload_v: Value = take_arg(&mut args, "payload")?;
        match crate::commands::settings::settings_save_agents(payload_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_save_ssh" => {
        let payload_v: Value = take_arg(&mut args, "payload")?;
        match crate::commands::settings::settings_save_ssh(payload_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_apply_ssh_patch" => {
        let payload_v: Value = take_arg(&mut args, "payload")?;
        match crate::commands::settings::settings_apply_ssh_patch(payload_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "settings_reset_ssh_known_host" => {
        let host_v: String = take_arg(&mut args, "host")?;
        let port_v: u16 = take_arg(&mut args, "port")?;
        match crate::commands::settings::settings_reset_ssh_known_host(host_v, port_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== subagent_store =====
    "subagent_identity_upsert" => {
        let input_v: SubagentIdentityUpsertInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_store::subagent_identity_upsert(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "subagent_identity_list" => {
        let input_v: SubagentIdentityListInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_store::subagent_identity_list(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "subagent_run_save" => {
        let input_v: SubagentRunSaveInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_store::subagent_run_save(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "subagent_run_list" => {
        let input_v: SubagentRunListInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_store::subagent_run_list(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "subagent_run_load" => {
        let input_v: SubagentRunLoadInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_store::subagent_run_load(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "subagent_run_prune" => {
        let input_v: SubagentRunPruneInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_store::subagent_run_prune(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "subagent_message_append" => {
        let input_v: SubagentMessageAppendInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_store::subagent_message_append(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "subagent_message_list" => {
        let input_v: SubagentMessageListInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_store::subagent_message_list(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== chat_history =====
    "chat_history_branch" => {
        let id_v: String = take_arg(&mut args, "id")?;
        let base_message_ref_v: ChatHistoryMessageRef = take_arg(&mut args, "base_message_ref")?;
        match crate::commands::chat_history::chat_history_branch(id_v, base_message_ref_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_list" => {
        let page_v: i64 = take_arg(&mut args, "page")?;
        let page_size_v: i64 = take_arg(&mut args, "page_size")?;
        let cwd_v: Option<String> = take_arg_opt(&mut args, "cwd")?;
        let cwd_empty_v: Option<bool> = take_arg_opt(&mut args, "cwd_empty")?;
        match crate::commands::chat_history::chat_history_list(page_v, page_size_v, cwd_v, cwd_empty_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_workdirs" => {
        match crate::commands::chat_history::chat_history_workdirs().await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_shared_list" => {
        let page_v: i64 = take_arg(&mut args, "page")?;
        let page_size_v: i64 = take_arg(&mut args, "page_size")?;
        match crate::commands::chat_history::chat_history_shared_list(page_v, page_size_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_search" => {
        let args_v: ChatHistorySearchArgs = take_arg(&mut args, "args")?;
        match crate::commands::chat_history::chat_history_search(args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_get_window" => {
        let id_v: String = take_arg(&mut args, "id")?;
        let max_messages_v: i64 = take_arg(&mut args, "max_messages")?;
        let before_offset_v: Option<i64> = take_arg_opt(&mut args, "before_offset")?;
        let expected_revision_v: Option<String> = take_arg_opt(&mut args, "expected_revision")?;
        let include_active_segment_v: bool = take_arg(&mut args, "include_active_segment")?;
        match crate::commands::chat_history::chat_history_get_window(id_v, max_messages_v, before_offset_v, expected_revision_v, include_active_segment_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_upsert" => {
        let input_v: ChatHistoryUpsertInput = take_arg(&mut args, "input")?;
        match crate::commands::chat_history::chat_history_upsert(input_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_upsert_active_segment" => {
        let input_v: ChatHistorySegmentMutationInput = take_arg(&mut args, "input")?;
        match crate::commands::chat_history::chat_history_upsert_active_segment(input_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_append_segment" => {
        let input_v: ChatHistorySegmentMutationInput = take_arg(&mut args, "input")?;
        match crate::commands::chat_history::chat_history_append_segment(input_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_rename" => {
        let id_v: String = take_arg(&mut args, "id")?;
        let title_v: String = take_arg(&mut args, "title")?;
        match crate::commands::chat_history::chat_history_rename(id_v, title_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_set_pinned" => {
        let id_v: String = take_arg(&mut args, "id")?;
        let is_pinned_v: bool = take_arg(&mut args, "is_pinned")?;
        match crate::commands::chat_history::chat_history_set_pinned(id_v, is_pinned_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_set_model" => {
        let id_v: String = take_arg(&mut args, "id")?;
        let selected_model_json_v: String = take_arg(&mut args, "selected_model_json")?;
        match crate::commands::chat_history::chat_history_set_model(id_v, selected_model_json_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_share_get" => {
        let id_v: String = take_arg(&mut args, "id")?;
        match crate::commands::chat_history::chat_history_share_get(id_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_share_set" => {
        let id_v: String = take_arg(&mut args, "id")?;
        let enabled_v: bool = take_arg(&mut args, "enabled")?;
        let redact_tool_content_v: Option<bool> = take_arg_opt(&mut args, "redact_tool_content")?;
        match crate::commands::chat_history::chat_history_share_set(id_v, enabled_v, redact_tool_content_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_delete" => {
        let id_v: String = take_arg(&mut args, "id")?;
        match crate::commands::chat_history::chat_history_delete(id_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "chat_history_replace_from_message" => {
        let id_v: String = take_arg(&mut args, "id")?;
        let base_message_ref_v: ChatHistoryMessageRef = take_arg(&mut args, "base_message_ref")?;
        let replacement_message_v: Value = take_arg(&mut args, "replacement_message")?;
        let max_messages_v: i64 = take_arg(&mut args, "max_messages")?;
        let expected_revision_v: String = take_arg(&mut args, "expected_revision")?;
        match crate::commands::chat_history::chat_history_replace_from_message(id_v, base_message_ref_v, replacement_message_v, max_messages_v, expected_revision_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== gateway =====
    "provider_usage_query" => {
        let provider_id_v: String = take_arg(&mut args, "provider_id")?;
        let refresh_v: bool = take_arg(&mut args, "refresh")?;
        match crate::commands::gateway::provider_usage_query(provider_id_v, refresh_v, &state.ctx.provider_usage_service).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "provider_usage_test" => {
        let provider_id_v: String = take_arg(&mut args, "provider_id")?;
        let config_json_v: String = take_arg(&mut args, "config_json")?;
        match crate::commands::gateway::provider_usage_test(provider_id_v, config_json_v, &state.ctx.provider_usage_service).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_connect" => {
        let payload_v: Option<Value> = take_arg_opt(&mut args, "payload")?;
        match crate::commands::gateway::gateway_connect(payload_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_disconnect" => {
        match crate::commands::gateway::gateway_disconnect(&state.ctx.gateway_controller) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_status" => {
        match crate::commands::gateway::gateway_status(&state.ctx.gateway_controller) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_nudge_connection" => {
        let reason_v: Option<String> = take_arg_opt(&mut args, "reason")?;
        let force_reconnect_v: Option<bool> = take_arg_opt(&mut args, "force_reconnect")?;
        match crate::commands::gateway::gateway_nudge_connection(reason_v, force_reconnect_v, &state.ctx.gateway_controller) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_send_chat_ingress_batch" => {
        let input_v: GatewayChatIngressBatchInput = take_arg(&mut args, "input")?;
        match crate::commands::gateway::gateway_send_chat_ingress_batch(input_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_commit_chat_checkpoint" => {
        let input_v: GatewayChatCheckpointInput = take_arg(&mut args, "input")?;
        match crate::commands::gateway::gateway_commit_chat_checkpoint(input_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_claim_next" => {
        let worker_id_v: String = take_arg(&mut args, "worker_id")?;
        let lease_ms_v: Option<u64> = take_arg_opt(&mut args, "lease_ms")?;
        match crate::commands::gateway::gateway_chat_claim_next(worker_id_v, lease_ms_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_mark_started" => {
        let request_id_v: String = take_arg(&mut args, "request_id")?;
        let conversation_id_v: String = take_arg(&mut args, "conversation_id")?;
        let worker_id_v: String = take_arg(&mut args, "worker_id")?;
        match crate::commands::gateway::gateway_chat_mark_started(request_id_v, conversation_id_v, worker_id_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_mark_local_started" => {
        let request_id_v: String = take_arg(&mut args, "request_id")?;
        let conversation_id_v: String = take_arg(&mut args, "conversation_id")?;
        match crate::commands::gateway::gateway_chat_mark_local_started(request_id_v, conversation_id_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_mark_local_cancelled" => {
        let request_id_v: String = take_arg(&mut args, "request_id")?;
        let conversation_id_v: String = take_arg(&mut args, "conversation_id")?;
        match crate::commands::gateway::gateway_chat_mark_local_cancelled(request_id_v, conversation_id_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_mark_queued_in_gui" => {
        let request_id_v: String = take_arg(&mut args, "request_id")?;
        let conversation_id_v: String = take_arg(&mut args, "conversation_id")?;
        let worker_id_v: String = take_arg(&mut args, "worker_id")?;
        match crate::commands::gateway::gateway_chat_mark_queued_in_gui(request_id_v, conversation_id_v, worker_id_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_complete" => {
        let request_id_v: String = take_arg(&mut args, "request_id")?;
        let conversation_id_v: String = take_arg(&mut args, "conversation_id")?;
        let worker_id_v: String = take_arg(&mut args, "worker_id")?;
        match crate::commands::gateway::gateway_chat_complete(request_id_v, conversation_id_v, worker_id_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_fail" => {
        let request_id_v: String = take_arg(&mut args, "request_id")?;
        let conversation_id_v: Option<String> = take_arg_opt(&mut args, "conversation_id")?;
        let error_code_v: String = take_arg(&mut args, "error_code")?;
        let message_v: String = take_arg(&mut args, "message")?;
        let terminal_v: bool = take_arg(&mut args, "terminal")?;
        let worker_id_v: String = take_arg(&mut args, "worker_id")?;
        match crate::commands::gateway::gateway_chat_fail(request_id_v, conversation_id_v, error_code_v, message_v, terminal_v, worker_id_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_cancel_request" => {
        let request_id_v: String = take_arg(&mut args, "request_id")?;
        let conversation_id_v: String = take_arg(&mut args, "conversation_id")?;
        let worker_id_v: String = take_arg(&mut args, "worker_id")?;
        match crate::commands::gateway::gateway_chat_cancel_request(request_id_v, conversation_id_v, worker_id_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_heartbeat" => {
        let request_id_v: String = take_arg(&mut args, "request_id")?;
        let worker_id_v: String = take_arg(&mut args, "worker_id")?;
        match crate::commands::gateway::gateway_chat_heartbeat(request_id_v, worker_id_v, &state.ctx.gateway_controller) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_runtime_heartbeat" => {
        let worker_id_v: String = take_arg(&mut args, "worker_id")?;
        let state_v: String = take_arg(&mut args, "state")?;
        let visible_v: bool = take_arg(&mut args, "visible")?;
        let active_run_count_v: u32 = take_arg(&mut args, "active_run_count")?;
        match crate::commands::gateway::gateway_chat_runtime_heartbeat(worker_id_v, state_v, visible_v, active_run_count_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_release_lease" => {
        let request_id_v: String = take_arg(&mut args, "request_id")?;
        let worker_id_v: String = take_arg(&mut args, "worker_id")?;
        match crate::commands::gateway::gateway_chat_release_lease(request_id_v, worker_id_v, &state.ctx.gateway_controller) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_chat_queue_respond" => {
        let input_v: GatewayChatQueueResponseInput = take_arg(&mut args, "input")?;
        match crate::commands::gateway::gateway_chat_queue_respond(input_v, &state.ctx.gateway_controller) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_publish_chat_queue_event" => {
        let input_v: GatewayChatQueueEventInput = take_arg(&mut args, "input")?;
        match crate::commands::gateway::gateway_publish_chat_queue_event(input_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_publish_settings_sync" => {
        let payload_v: Value = take_arg(&mut args, "payload")?;
        match crate::commands::gateway::gateway_publish_settings_sync(payload_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_tunnel_state" => {
        match crate::commands::gateway::gateway_tunnel_state(&state.ctx.gateway_controller) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_tunnel_create" => {
        let input_v: GatewayTunnelCreateInput = take_arg(&mut args, "input")?;
        match crate::commands::gateway::gateway_tunnel_create(input_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_tunnel_update" => {
        let input_v: GatewayTunnelUpdateInput = take_arg(&mut args, "input")?;
        match crate::commands::gateway::gateway_tunnel_update(input_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_tunnel_close" => {
        let tunnel_id_v: String = take_arg(&mut args, "tunnel_id")?;
        match crate::commands::gateway::gateway_tunnel_close(tunnel_id_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "gateway_tunnel_check" => {
        let tunnel_id_v: Option<String> = take_arg_opt(&mut args, "tunnel_id")?;
        match crate::commands::gateway::gateway_tunnel_check(tunnel_id_v, &state.ctx.gateway_controller).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "workspace_watch_set" => {
        let workdirs_v: Vec<String> = take_arg(&mut args, "workdirs")?;
        match crate::commands::gateway::workspace_watch_set(workdirs_v, &state.ctx.gateway_controller) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== mcp =====
    "mcp_list_tools" => {
        let servers_v: Vec<McpServerConfig> = take_arg(&mut args, "servers")?;
        match crate::commands::mcp::mcp_list_tools(&state.mcp_runtime, servers_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "mcp_call_tool" => {
        let server_id_v: String = take_arg(&mut args, "server_id")?;
        let tool_name_v: String = take_arg(&mut args, "tool_name")?;
        let arguments_v: Value = take_arg(&mut args, "arguments")?;
        let run_id_v: Option<String> = take_arg_opt(&mut args, "run_id")?;
        match crate::commands::mcp::mcp_call_tool(&state.mcp_runtime, &state.shell_runs, server_id_v, tool_name_v, arguments_v, run_id_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "mcp_runtime_status" => {
        let server_id_v: String = take_arg(&mut args, "server_id")?;
        match crate::commands::mcp::mcp_runtime_status(&state.mcp_runtime, server_id_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "mcp_stop_server" => {
        let server_id_v: String = take_arg(&mut args, "server_id")?;
        match crate::commands::mcp::mcp_stop_server(&state.mcp_runtime, server_id_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "mcp_test_server" => {
        let server_v: McpServerConfig = take_arg(&mut args, "server")?;
        let include_schema_v: Option<bool> = take_arg_opt(&mut args, "include_schema")?;
        let persist_v: Option<bool> = take_arg_opt(&mut args, "persist")?;
        match crate::commands::mcp::mcp_test_server(&state.mcp_runtime, server_v, include_schema_v, persist_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "mcp_restart_server" => {
        let server_v: McpServerConfig = take_arg(&mut args, "server")?;
        let include_schema_v: Option<bool> = take_arg_opt(&mut args, "include_schema")?;
        let persist_v: Option<bool> = take_arg_opt(&mut args, "persist")?;
        match crate::commands::mcp::mcp_restart_server(&state.mcp_runtime, server_v, include_schema_v, persist_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== memory =====
    "memory_list" => {
        let args_v: MemoryListArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_list(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_read" => {
        let args_v: MemoryReadArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_read(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_search" => {
        let args_v: MemorySearchArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_search(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_write" => {
        let args_v: MemoryWriteArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_write(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_update" => {
        let args_v: MemoryUpdateArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_update(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_delete" => {
        let args_v: MemoryDeleteArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_delete(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_delete_project" => {
        let args_v: MemoryDeleteProjectArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_delete_project(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_accept" => {
        let args_v: MemoryAcceptArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_accept(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_apply_batch" => {
        let args_v: MemoryBatchArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_apply_batch(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_organize_run_create" => {
        let args_v: MemoryOrganizeRunCreateArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_organize_run_create(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_organize_run_update" => {
        let args_v: MemoryOrganizeRunUpdateArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_organize_run_update(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_organize_run_list" => {
        let args_v: Option<MemoryOrganizeRunListArgs> = take_arg_opt(&mut args, "args")?;
        match crate::commands::memory::memory_organize_run_list(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_organize_run_read" => {
        let args_v: MemoryOrganizeRunReadArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_organize_run_read(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_organize_run_clear_history" => {
        match crate::commands::memory::memory_organize_run_clear_history(&state.ctx.memory_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_organize_due_claim" => {
        let args_v: MemoryOrganizeDueClaimArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_organize_due_claim(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_organize_due_complete" => {
        let args_v: MemoryOrganizeRunUpdateArgs = take_arg(&mut args, "args")?;
        match crate::commands::memory::memory_organize_due_complete(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_index_overview" => {
        let workdir_v: Option<String> = take_arg_opt(&mut args, "workdir")?;
        match crate::commands::memory::memory_index_overview(&state.ctx.memory_store, workdir_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_paths_info" => {
        match crate::commands::memory::memory_paths_info(&state.ctx.memory_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_recent_rejections" => {
        let args_v: Option<MemoryRecentRejectionsArgs> = take_arg_opt(&mut args, "args")?;
        match crate::commands::memory::memory_recent_rejections(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_today_local_date" => {
        let rollover_hour_v: Option<u32> = take_arg_opt(&mut args, "rollover_hour")?;
        match crate::commands::memory::memory_today_local_date(&state.ctx.memory_store, rollover_hour_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_today_daily" => {
        let rollover_hour_v: Option<u32> = take_arg_opt(&mut args, "rollover_hour")?;
        match crate::commands::memory::memory_today_daily(&state.ctx.memory_store, rollover_hour_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_quota_summary" => {
        let args_v: Option<MemoryQuotaSummaryArgs> = take_arg_opt(&mut args, "args")?;
        match crate::commands::memory::memory_quota_summary(&state.ctx.memory_store, args_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "memory_wipe_all" => {
        match crate::commands::memory::memory_wipe_all(&state.ctx.memory_store).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== process =====
    "managed_process_start" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let command_v: String = take_arg(&mut args, "command")?;
        let cwd_v: Option<String> = take_arg_opt(&mut args, "cwd")?;
        let label_v: Option<String> = take_arg_opt(&mut args, "label")?;
        let isolated_v: Option<bool> = take_arg_opt(&mut args, "isolated")?;
        match crate::commands::process::managed_process_start(&state.ctx.managed_process_registry, workdir_v, command_v, cwd_v, label_v, isolated_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "managed_process_status" => {
        let process_id_v: Option<String> = take_arg_opt(&mut args, "process_id")?;
        match crate::commands::process::managed_process_status(&state.ctx.managed_process_registry, process_id_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "managed_process_stop" => {
        let process_id_v: String = take_arg(&mut args, "process_id")?;
        match crate::commands::process::managed_process_stop(&state.ctx.managed_process_registry, process_id_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "managed_process_read_log" => {
        let process_id_v: String = take_arg(&mut args, "process_id")?;
        let max_bytes_v: Option<u64> = take_arg_opt(&mut args, "max_bytes")?;
        match crate::commands::process::managed_process_read_log(&state.ctx.managed_process_registry, process_id_v, max_bytes_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "managed_process_snapshot" => {
        match crate::commands::process::managed_process_snapshot(&state.ctx.managed_process_registry) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "managed_process_clear" => {
        let process_id_v: Option<String> = take_arg_opt(&mut args, "process_id")?;
        match crate::commands::process::managed_process_clear(&state.ctx.managed_process_registry, process_id_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== sftp =====
    "sftp_list" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let side_v: String = take_arg(&mut args, "side")?;
        let path_v: Option<String> = take_arg_opt(&mut args, "path")?;
        match crate::commands::sftp::sftp_list(&state.ctx.sftp_registry, session_id_v, project_path_key_v, workdir_v, side_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "sftp_stat" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let side_v: String = take_arg(&mut args, "side")?;
        let path_v: Option<String> = take_arg_opt(&mut args, "path")?;
        match crate::commands::sftp::sftp_stat(&state.ctx.sftp_registry, session_id_v, project_path_key_v, workdir_v, side_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "sftp_read_text" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        let path_v: String = take_arg(&mut args, "path")?;
        let offset_v: Option<u64> = take_arg_opt(&mut args, "offset")?;
        let max_bytes_v: Option<usize> = take_arg_opt(&mut args, "max_bytes")?;
        match crate::commands::sftp::sftp_read_text(&state.ctx.sftp_registry, session_id_v, project_path_key_v, path_v, offset_v, max_bytes_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "sftp_write_text" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        let path_v: String = take_arg(&mut args, "path")?;
        let content_v: String = take_arg(&mut args, "content")?;
        let overwrite_v: Option<bool> = take_arg_opt(&mut args, "overwrite")?;
        let create_parent_dirs_v: Option<bool> = take_arg_opt(&mut args, "create_parent_dirs")?;
        match crate::commands::sftp::sftp_write_text(&state.ctx.sftp_registry, session_id_v, project_path_key_v, path_v, content_v, overwrite_v, create_parent_dirs_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "sftp_mkdir" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let side_v: String = take_arg(&mut args, "side")?;
        let path_v: String = take_arg(&mut args, "path")?;
        match crate::commands::sftp::sftp_mkdir(&state.ctx.sftp_registry, session_id_v, project_path_key_v, workdir_v, side_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "sftp_rename" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let side_v: String = take_arg(&mut args, "side")?;
        let from_path_v: String = take_arg(&mut args, "from_path")?;
        let to_path_v: String = take_arg(&mut args, "to_path")?;
        match crate::commands::sftp::sftp_rename(&state.ctx.sftp_registry, session_id_v, project_path_key_v, workdir_v, side_v, from_path_v, to_path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "sftp_delete" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let side_v: String = take_arg(&mut args, "side")?;
        let path_v: String = take_arg(&mut args, "path")?;
        let recursive_v: Option<bool> = take_arg_opt(&mut args, "recursive")?;
        match crate::commands::sftp::sftp_delete(&state.ctx.sftp_registry, session_id_v, project_path_key_v, workdir_v, side_v, path_v, recursive_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "sftp_transfer" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let direction_v: String = take_arg(&mut args, "direction")?;
        let source_path_v: String = take_arg(&mut args, "source_path")?;
        let target_path_v: String = take_arg(&mut args, "target_path")?;
        let recursive_v: Option<bool> = take_arg_opt(&mut args, "recursive")?;
        let overwrite_v: Option<bool> = take_arg_opt(&mut args, "overwrite")?;
        match crate::commands::sftp::sftp_transfer(&state.ctx.sftp_registry, session_id_v, project_path_key_v, workdir_v, direction_v, source_path_v, target_path_v, recursive_v, overwrite_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "sftp_cancel_transfer" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let transfer_id_v: String = take_arg(&mut args, "transfer_id")?;
        match crate::commands::sftp::sftp_cancel_transfer(&state.ctx.sftp_registry, session_id_v, transfer_id_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "sftp_transfer_status" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let transfer_id_v: String = take_arg(&mut args, "transfer_id")?;
        match crate::commands::sftp::sftp_transfer_status(&state.ctx.sftp_registry, session_id_v, transfer_id_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== terminal =====
    "terminal_shell_options" => {
        to_value(crate::commands::terminal::terminal_shell_options())
    },
    "terminal_list" => {
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        to_value(crate::commands::terminal::terminal_list(&state.ctx.terminal_registry, project_path_key_v))
    },
    "terminal_create" => {
        let cwd_v: String = take_arg(&mut args, "cwd")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        let shell_v: Option<String> = take_arg_opt(&mut args, "shell")?;
        let title_v: Option<String> = take_arg_opt(&mut args, "title")?;
        let cols_v: Option<u16> = take_arg_opt(&mut args, "cols")?;
        let rows_v: Option<u16> = take_arg_opt(&mut args, "rows")?;
        match crate::commands::terminal::terminal_create(&state.ctx.terminal_registry, cwd_v, project_path_key_v, shell_v, title_v, cols_v, rows_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_create_ssh" => {
        let cwd_v: String = take_arg(&mut args, "cwd")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        let ssh_host_id_v: String = take_arg(&mut args, "ssh_host_id")?;
        let title_v: Option<String> = take_arg_opt(&mut args, "title")?;
        let cols_v: Option<u16> = take_arg_opt(&mut args, "cols")?;
        let rows_v: Option<u16> = take_arg_opt(&mut args, "rows")?;
        let sftp_enabled_v: Option<bool> = take_arg_opt(&mut args, "sftp_enabled")?;
        match crate::commands::terminal::terminal_create_ssh(&state.ctx.terminal_registry, cwd_v, project_path_key_v, ssh_host_id_v, title_v, cols_v, rows_v, sftp_enabled_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_answer_ssh_prompt" => {
        let prompt_id_v: String = take_arg(&mut args, "prompt_id")?;
        let prompt_answer_v: Option<String> = take_arg_opt(&mut args, "prompt_answer")?;
        let trust_host_key_v: Option<bool> = take_arg_opt(&mut args, "trust_host_key")?;
        match crate::commands::terminal::terminal_answer_ssh_prompt(&state.ctx.terminal_registry, prompt_id_v, prompt_answer_v, trust_host_key_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_cancel_ssh_prompt" => {
        let prompt_id_v: String = take_arg(&mut args, "prompt_id")?;
        match crate::commands::terminal::terminal_cancel_ssh_prompt(&state.ctx.terminal_registry, prompt_id_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_ssh_reconnect" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        match crate::commands::terminal::terminal_ssh_reconnect(&state.ctx.terminal_registry, session_id_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_ssh_latency" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        match crate::commands::terminal::terminal_ssh_latency(&state.ctx.terminal_registry, session_id_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_ssh_exec" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let command_v: String = take_arg(&mut args, "command")?;
        let cwd_v: Option<String> = take_arg_opt(&mut args, "cwd")?;
        let timeout_ms_v: Option<u64> = take_arg_opt(&mut args, "timeout_ms")?;
        let max_bytes_v: Option<usize> = take_arg_opt(&mut args, "max_bytes")?;
        let run_id_v: Option<String> = take_arg_opt(&mut args, "run_id")?;
        match crate::commands::terminal::terminal_ssh_exec(&state.ctx.terminal_registry, &state.shell_runs, session_id_v, command_v, cwd_v, timeout_ms_v, max_bytes_v, run_id_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_ssh_local_forward_start" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        let remote_host_v: String = take_arg(&mut args, "remote_host")?;
        let remote_port_v: u32 = take_arg(&mut args, "remote_port")?;
        let local_port_v: Option<u32> = take_arg_opt(&mut args, "local_port")?;
        match crate::commands::terminal::terminal_ssh_local_forward_start(&state.ctx.terminal_registry, session_id_v, project_path_key_v, remote_host_v, remote_port_v, local_port_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_ssh_local_forward_list" => {
        let session_id_v: Option<String> = take_arg_opt(&mut args, "session_id")?;
        let project_path_key_v: Option<String> = take_arg_opt(&mut args, "project_path_key")?;
        match crate::commands::terminal::terminal_ssh_local_forward_list(&state.ctx.terminal_registry, session_id_v, project_path_key_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_ssh_local_forward_stop" => {
        let forward_id_v: String = take_arg(&mut args, "forward_id")?;
        let session_id_v: Option<String> = take_arg_opt(&mut args, "session_id")?;
        match crate::commands::terminal::terminal_ssh_local_forward_stop(&state.ctx.terminal_registry, forward_id_v, session_id_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_ssh_local_forward_check_port" => {
        let local_port_v: u32 = take_arg(&mut args, "local_port")?;
        match crate::commands::terminal::terminal_ssh_local_forward_check_port(local_port_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "ssh_terminal_tabs_list" => {
        let project_path_key_v: String = take_arg(&mut args, "project_path_key")?;
        match crate::commands::terminal::ssh_terminal_tabs_list(&state.ctx.terminal_registry, project_path_key_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "ssh_terminal_tab_open" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let kind_v: String = take_arg(&mut args, "kind")?;
        match crate::commands::terminal::ssh_terminal_tab_open(&state.ctx.terminal_registry, session_id_v, kind_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "ssh_terminal_tab_close" => {
        let tab_id_v: String = take_arg(&mut args, "tab_id")?;
        match crate::commands::terminal::ssh_terminal_tab_close(&state.ctx.terminal_registry, tab_id_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_stream_attach" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let max_bytes_v: Option<usize> = take_arg_opt(&mut args, "max_bytes")?;
        match crate::commands::terminal::terminal_stream_attach(&state.ctx.terminal_registry, session_id_v, max_bytes_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_stream_input" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let bytes_v: Vec<u8> = take_arg(&mut args, "bytes")?;
        match crate::commands::terminal::terminal_stream_input(&state.ctx.terminal_registry, session_id_v, bytes_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_stream_resize" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let cols_v: u16 = take_arg(&mut args, "cols")?;
        let rows_v: u16 = take_arg(&mut args, "rows")?;
        match crate::commands::terminal::terminal_stream_resize(&state.ctx.terminal_registry, session_id_v, cols_v, rows_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_rename" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        let title_v: String = take_arg(&mut args, "title")?;
        match crate::commands::terminal::terminal_rename(&state.ctx.terminal_registry, session_id_v, title_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_close" => {
        let session_id_v: String = take_arg(&mut args, "session_id")?;
        match crate::commands::terminal::terminal_close(&state.ctx.terminal_registry, &state.ctx.sftp_registry, session_id_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_close_project" => {
        let project_path_key_v: String = take_arg(&mut args, "project_path_key")?;
        match crate::commands::terminal::terminal_close_project(&state.ctx.terminal_registry, &state.ctx.sftp_registry, project_path_key_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "terminal_read_tail" => {
        let project_path_key_v: String = take_arg(&mut args, "project_path_key")?;
        let session_id_v: Option<String> = take_arg_opt(&mut args, "session_id")?;
        let max_bytes_v: Option<usize> = take_arg_opt(&mut args, "max_bytes")?;
        match crate::commands::terminal::terminal_read_tail(&state.ctx.terminal_registry, project_path_key_v, session_id_v, max_bytes_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== shell =====
    "shell_run" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let command_v: String = take_arg(&mut args, "command")?;
        let cwd_v: Option<String> = take_arg_opt(&mut args, "cwd")?;
        let timeout_ms_v: Option<u64> = take_arg_opt(&mut args, "timeout_ms")?;
        let max_timeout_ms_v: Option<u64> = take_arg_opt(&mut args, "max_timeout_ms")?;
        let provider_id_v: Option<String> = take_arg_opt(&mut args, "provider_id")?;
        let run_id_v: Option<String> = take_arg_opt(&mut args, "run_id")?;
        match crate::commands::shell::shell_run(&state.shell_runs, workdir_v, command_v, cwd_v, timeout_ms_v, max_timeout_ms_v, provider_id_v, run_id_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "runtime_cancel" => {
        let run_id_v: String = take_arg(&mut args, "run_id")?;
        to_value(crate::commands::shell::runtime_cancel(&state.shell_runs, run_id_v))
    },
        // ===== chat_file_links =====
    "open_chat_file_link" => {
        let conversation_id_v: String = take_arg(&mut args, "conversation_id")?;
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        let source_v: String = take_arg(&mut args, "source")?;
        let line_v: Option<u32> = take_arg_opt(&mut args, "line")?;
        let end_line_v: Option<u32> = take_arg_opt(&mut args, "end_line")?;
        let column_v: Option<u32> = take_arg_opt(&mut args, "column")?;
        let open_in_file_manager_v: Option<bool> = take_arg_opt(&mut args, "open_in_file_manager")?;
        match crate::commands::chat_file_links::open_chat_file_link(conversation_id_v, workdir_v, path_v, source_v, line_v, end_line_v, column_v, open_in_file_manager_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
        // ===== fs =====
    "fs_read_image_source" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let source_v: String = take_arg(&mut args, "source")?;
        let source_type_v: Option<String> = take_arg_opt(&mut args, "source_type")?;
        let mime_type_v: Option<String> = take_arg_opt(&mut args, "mime_type")?;
        match crate::commands::fs::fs_read_image_source(workdir_v, source_v, source_type_v, mime_type_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_read_workspace_image" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        match crate::commands::fs::fs_read_workspace_image(workdir_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_read_text" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        let start_line_v: Option<usize> = take_arg_opt(&mut args, "start_line")?;
        let limit_v: Option<usize> = take_arg_opt(&mut args, "limit")?;
        let page_start_v: Option<usize> = take_arg_opt(&mut args, "page_start")?;
        let page_limit_v: Option<usize> = take_arg_opt(&mut args, "page_limit")?;
        let cell_start_v: Option<usize> = take_arg_opt(&mut args, "cell_start")?;
        let cell_limit_v: Option<usize> = take_arg_opt(&mut args, "cell_limit")?;
        match crate::commands::fs::fs_read_text(workdir_v, path_v, start_line_v, limit_v, page_start_v, page_limit_v, cell_start_v, cell_limit_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_read_editable_text" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        match crate::commands::fs::fs_read_editable_text(workdir_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_path_status" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        match crate::commands::fs::fs_path_status(workdir_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_write_text" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        let content_v: String = take_arg(&mut args, "content")?;
        let mode_v: String = take_arg(&mut args, "mode")?;
        let expected_mtime_ms_v: Option<u64> = take_arg_opt(&mut args, "expected_mtime_ms")?;
        let expected_content_hash_v: Option<String> = take_arg_opt(&mut args, "expected_content_hash")?;
        match crate::commands::fs::fs_write_text(workdir_v, path_v, content_v, mode_v, expected_mtime_ms_v, expected_content_hash_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_edit_text" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        let old_string_v: String = take_arg(&mut args, "old_string")?;
        let new_string_v: String = take_arg(&mut args, "new_string")?;
        let expected_replacements_v: Option<usize> = take_arg_opt(&mut args, "expected_replacements")?;
        let replace_all_v: Option<bool> = take_arg_opt(&mut args, "replace_all")?;
        let expected_mtime_ms_v: Option<u64> = take_arg_opt(&mut args, "expected_mtime_ms")?;
        let expected_content_hash_v: Option<String> = take_arg_opt(&mut args, "expected_content_hash")?;
        match crate::commands::fs::fs_edit_text(workdir_v, path_v, old_string_v, new_string_v, expected_replacements_v, replace_all_v, expected_mtime_ms_v, expected_content_hash_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_delete" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        match crate::commands::fs::fs_delete(workdir_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_open_workspace_path" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        let mode_v: Option<String> = take_arg_opt(&mut args, "mode")?;
        match crate::commands::fs::fs_open_workspace_path(workdir_v, path_v, mode_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_create_dir" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        match crate::commands::fs::fs_create_dir(workdir_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_rename" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let from_path_v: String = take_arg(&mut args, "from_path")?;
        let to_path_v: String = take_arg(&mut args, "to_path")?;
        match crate::commands::fs::fs_rename(workdir_v, from_path_v, to_path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_roots" => {
        match crate::commands::fs::fs_roots().await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "fs_list_dirs" => {
        let path_v: String = take_arg(&mut args, "path")?;
        let max_results_v: Option<usize> = take_arg_opt(&mut args, "max_results")?;
        match crate::commands::fs::fs_list_dirs(path_v, max_results_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "fs_list" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: Option<String> = take_arg_opt(&mut args, "path")?;
        let depth_v: Option<usize> = take_arg_opt(&mut args, "depth")?;
        let offset_v: Option<usize> = take_arg_opt(&mut args, "offset")?;
        let max_results_v: Option<usize> = take_arg_opt(&mut args, "max_results")?;
        let show_hidden_v: Option<bool> = take_arg_opt(&mut args, "show_hidden")?;
        match crate::commands::fs::fs_list(workdir_v, path_v, depth_v, offset_v, max_results_v, show_hidden_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_glob" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: Option<String> = take_arg_opt(&mut args, "path")?;
        let pattern_v: String = take_arg(&mut args, "pattern")?;
        let offset_v: Option<usize> = take_arg_opt(&mut args, "offset")?;
        let max_results_v: Option<usize> = take_arg_opt(&mut args, "max_results")?;
        let sort_by_v: Option<String> = take_arg_opt(&mut args, "sort_by")?;
        match crate::commands::fs::fs_glob(workdir_v, path_v, pattern_v, offset_v, max_results_v, sort_by_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_grep" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: Option<String> = take_arg_opt(&mut args, "path")?;
        let pattern_v: String = take_arg(&mut args, "pattern")?;
        let file_pattern_v: Option<String> = take_arg_opt(&mut args, "file_pattern")?;
        let ignore_case_v: Option<bool> = take_arg_opt(&mut args, "ignore_case")?;
        let output_mode_v: Option<String> = take_arg_opt(&mut args, "output_mode")?;
        let head_limit_v: Option<usize> = take_arg_opt(&mut args, "head_limit")?;
        let offset_v: Option<usize> = take_arg_opt(&mut args, "offset")?;
        let context_v: Option<usize> = take_arg_opt(&mut args, "context")?;
        let multiline_v: Option<bool> = take_arg_opt(&mut args, "multiline")?;
        match crate::commands::fs::fs_grep(workdir_v, path_v, pattern_v, file_pattern_v, ignore_case_v, output_mode_v, head_limit_v, offset_v, context_v, multiline_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(format!("{e:?}")),
        }
    },
    "fs_mention_list" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let max_results_v: Option<usize> = take_arg_opt(&mut args, "max_results")?;
        let query_v: Option<String> = take_arg_opt(&mut args, "query")?;
        let show_hidden_v: Option<bool> = take_arg_opt(&mut args, "show_hidden")?;
        match crate::commands::fs::fs_mention_list(workdir_v, max_results_v, query_v, show_hidden_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== git =====
    "git_status" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        match crate::commands::git::git_status(workdir_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_discover_repositories" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        match crate::commands::git::git_discover_repositories(workdir_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_branches" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        match crate::commands::git::git_branches(workdir_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_switch_branch" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let branch_v: String = take_arg(&mut args, "branch")?;
        let kind_v: Option<String> = take_arg_opt(&mut args, "kind")?;
        match crate::commands::git::git_switch_branch(workdir_v, branch_v, kind_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_create_branch" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let branch_v: String = take_arg(&mut args, "branch")?;
        let start_point_v: Option<String> = take_arg_opt(&mut args, "start_point")?;
        match crate::commands::git::git_create_branch(workdir_v, branch_v, start_point_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_init" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let branch_v: Option<String> = take_arg_opt(&mut args, "branch")?;
        let user_name_v: Option<String> = take_arg_opt(&mut args, "user_name")?;
        let user_email_v: Option<String> = take_arg_opt(&mut args, "user_email")?;
        match crate::commands::git::git_init(workdir_v, branch_v, user_name_v, user_email_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_clone_repository" => {
        let parent_v: String = take_arg(&mut args, "parent")?;
        let name_v: String = take_arg(&mut args, "name")?;
        let remote_url_v: String = take_arg(&mut args, "remote_url")?;
        let branch_v: Option<String> = take_arg_opt(&mut args, "branch")?;
        match crate::commands::git::git_clone_repository(parent_v, name_v, remote_url_v, branch_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_clone_repository_start" => {
        let parent_v: String = take_arg(&mut args, "parent")?;
        let name_v: String = take_arg(&mut args, "name")?;
        let remote_url_v: String = take_arg(&mut args, "remote_url")?;
        let branch_v: Option<String> = take_arg_opt(&mut args, "branch")?;
        match crate::commands::git::git_clone_repository_start(&state.ctx.git_clone_task_registry, parent_v, name_v, remote_url_v, branch_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_clone_repository_tasks" => {
        match crate::commands::git::git_clone_repository_tasks(&state.ctx.git_clone_task_registry) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_clone_repository_cancel" => {
        let task_id_v: String = take_arg(&mut args, "task_id")?;
        match crate::commands::git::git_clone_repository_cancel(&state.ctx.git_clone_task_registry, task_id_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_clone_repository_dismiss" => {
        let task_id_v: String = take_arg(&mut args, "task_id")?;
        match crate::commands::git::git_clone_repository_dismiss(&state.ctx.git_clone_task_registry, task_id_v) {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_list_remote_branches" => {
        let remote_url_v: String = take_arg(&mut args, "remote_url")?;
        match crate::commands::git::git_list_remote_branches(remote_url_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_diff" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let mode_v: Option<String> = take_arg_opt(&mut args, "mode")?;
        let path_v: Option<String> = take_arg_opt(&mut args, "path")?;
        match crate::commands::git::git_diff(workdir_v, mode_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_log" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let limit_v: Option<usize> = take_arg_opt(&mut args, "limit")?;
        let skip_v: Option<usize> = take_arg_opt(&mut args, "skip")?;
        match crate::commands::git::git_log(workdir_v, limit_v, skip_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_commit_details" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let commit_v: String = take_arg(&mut args, "commit")?;
        match crate::commands::git::git_commit_details(workdir_v, commit_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_compare_commit_with_remote" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let commit_v: String = take_arg(&mut args, "commit")?;
        match crate::commands::git::git_compare_commit_with_remote(workdir_v, commit_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_commit_diff" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let commit_v: String = take_arg(&mut args, "commit")?;
        let path_v: Option<String> = take_arg_opt(&mut args, "path")?;
        match crate::commands::git::git_commit_diff(workdir_v, commit_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_stage" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        match crate::commands::git::git_stage(workdir_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_stage_all" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        match crate::commands::git::git_stage_all(workdir_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_unstage" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        match crate::commands::git::git_unstage(workdir_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_unstage_all" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        match crate::commands::git::git_unstage_all(workdir_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_discard" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        let old_path_v: Option<String> = take_arg_opt(&mut args, "old_path")?;
        match crate::commands::git::git_discard(workdir_v, path_v, old_path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_discard_all" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        match crate::commands::git::git_discard_all(workdir_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_add_to_gitignore" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        match crate::commands::git::git_add_to_gitignore(workdir_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_open_system_file_location" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let path_v: String = take_arg(&mut args, "path")?;
        match crate::commands::git::git_open_system_file_location(workdir_v, path_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_commit" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let message_v: String = take_arg(&mut args, "message")?;
        match crate::commands::git::git_commit(workdir_v, message_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_fetch" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        match crate::commands::git::git_fetch(workdir_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_pull" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        match crate::commands::git::git_pull(workdir_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_set_remote" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let remote_url_v: String = take_arg(&mut args, "remote_url")?;
        match crate::commands::git::git_set_remote(workdir_v, remote_url_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_push" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        match crate::commands::git::git_push(workdir_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_delete_branch" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let branch_v: String = take_arg(&mut args, "branch")?;
        let force_v: Option<bool> = take_arg_opt(&mut args, "force")?;
        match crate::commands::git::git_delete_branch(workdir_v, branch_v, force_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_rename_branch" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let branch_v: String = take_arg(&mut args, "branch")?;
        let new_branch_v: String = take_arg(&mut args, "new_branch")?;
        match crate::commands::git::git_rename_branch(workdir_v, branch_v, new_branch_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_stash_push" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        let message_v: Option<String> = take_arg_opt(&mut args, "message")?;
        match crate::commands::git::git_stash_push(workdir_v, message_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "git_stash_pop" => {
        let workdir_v: String = take_arg(&mut args, "workdir")?;
        match crate::commands::git::git_stash_pop(workdir_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== subagent_worktree =====
    "subagent_worktree_create" => {
        let input_v: SubagentWorktreeCreateInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_worktree::subagent_worktree_create(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "subagent_worktree_status" => {
        let input_v: SubagentWorktreeStatusInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_worktree::subagent_worktree_status(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "subagent_worktree_apply" => {
        let input_v: SubagentWorktreeApplyInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_worktree::subagent_worktree_apply(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
    "subagent_worktree_cleanup" => {
        let input_v: SubagentWorktreeCleanupInput = take_arg(&mut args, "input")?;
        match crate::commands::subagent_worktree::subagent_worktree_cleanup(input_v).await {
            Ok(v) => to_value(v),
            Err(e) => Err(e),
        }
    },
        // ===== proxy =====
    "proxy_get_server_info" => {
        to_value(crate::services::proxy::proxy_get_server_info(&state.proxy_server))
    },
        _ => Err(format!("unknown command: {cmd}")),
    }
}

/// Build the axum state (registries that are not part of AppContext).
pub fn build_state(ctx: Arc<AppContext>, emitter: Arc<WsEventEmitter>) -> Result<HeadlessState, String> {
    let mcp_runtime = Arc::new(crate::commands::mcp::McpRuntimeManager::default());
    let shell_runs = Arc::new(ShellRunRegistry::default());
    let hook_scopes = Arc::new(crate::commands::hook::HookScopeRegistry::default());
    let proxy_server = crate::services::proxy::start_proxy_server()?;
    Ok(HeadlessState { ctx, emitter, mcp_runtime, shell_runs, hook_scopes, proxy_server })
}

async fn health(AxumState(_state): AxumState<HeadlessState>) -> Json<Value> {
    Json(serde_json::json!({
        "ok": true,
        "version": crate::app_version(),
        "mode": "headless",
    }))
}

#[derive(Deserialize)]
struct InvokeRequest {
    cmd: String,
    args: Option<Value>,
}

async fn invoke_handler(
    AxumState(state): AxumState<HeadlessState>,
    Json(req): Json<InvokeRequest>,
) -> Json<Value> {
    let args = req.args.unwrap_or(Value::Null);
    match dispatch(&state, &req.cmd, args).await {
        Ok(value) => Json(serde_json::json!({ "ok": true, "value": value })),
        Err(error) => Json(serde_json::json!({ "ok": false, "error": error })),
    }
}

async fn ws_handler(
    ws: WebSocketUpgrade,
    AxumState(state): AxumState<HeadlessState>,
) -> impl IntoResponse {
    ws.on_upgrade(move |socket| handle_ws(socket, state))
}

async fn handle_ws(mut socket: WebSocket, state: HeadlessState) {
    let mut rx = state.emitter.subscribe();
    loop {
        match rx.recv().await {
            Ok(event) => {
                let text = match serde_json::to_string(&event) {
                    Ok(t) => t,
                    Err(_) => continue,
                };
                if socket.send(Message::Text(text.into())).await.is_err() {
                    break;
                }
            }
            Err(broadcast::error::RecvError::Lagged(_)) => continue,
            Err(broadcast::error::RecvError::Closed) => break,
        }
    }
}

pub fn build_router(state: HeadlessState) -> Router {
    Router::new()
        .route("/health", get(health))
        .route("/api/invoke", post(invoke_handler))
        .route("/ws", get(ws_handler))
        .with_state(state)
}

/// Run the headless server. Port from `LIVEAGENT_HEADLESS_PORT` (default 17890).
pub async fn serve() -> Result<(), String> {
    let port = std::env::var("LIVEAGENT_HEADLESS_PORT")
        .ok()
        .and_then(|p| p.parse::<u16>().ok())
        .unwrap_or(17890);
    let (tx, _) = broadcast::channel(1024);
    let emitter = Arc::new(WsEventEmitter::new(tx));
    let ws_emitter = Arc::clone(&emitter);
    let emitter_dyn: Arc<dyn crate::events::EventEmitter> = ws_emitter;
    let ctx = AppContext::new(emitter_dyn);
    let state = build_state(ctx, emitter).map_err(|e| format!("headless state: {e}"))?;
    let app = build_router(state);
    let listener = tokio::net::TcpListener::bind(("127.0.0.1", port))
        .await
        .map_err(|e| format!("bind 127.0.0.1:{port}: {e}"))?;
    eprintln!("LiveAgent headless listening on http://127.0.0.1:{port}");
    axum::serve(listener, app).await.map_err(|e| e.to_string())
}
