// AUTO-GENERATED by /tmp/gen_adapters.py — do not edit by hand.
// Desktop-only thin adapters that re-attach #[tauri::command] to the
// tauri-free business functions in crate::commands. Command names stay
// identical to the pre-refactor ones (P1.1 PR-B).
#![cfg(feature = "desktop")]

use std::sync::Arc;
use serde_json::Value;

use crate::commands::app::{CloseWindowBehaviorState, GlobalShortcutBinding, GlobalShortcutFailure, GlobalShortcutRegistry, MacOsTrafficLightMetrics, RuntimePlatformResponse, WindowPinState};
use crate::commands::chat_file_links::{ChatFileLinkError, ChatFileLinkOpenResponse};
use crate::commands::chat_history::{ChatHistoryListResponse, ChatHistoryMessageRef, ChatHistorySearchArgs, ChatHistorySearchResponse, ChatHistorySegmentMutationInput, ChatHistoryShareStatus, ChatHistorySummary, ChatHistoryUpsertInput, ChatHistoryWindowRecord, ChatHistoryWorkdirsResponse};
use crate::commands::fs::{CreateDirResponse, DeleteResponse, EditTextResponse, FsCommandError, FsListDirsResponse, FsRootsResponse, GlobResponse, GrepResponse, ListResponse, MentionListResponse, OpenWorkspacePathResponse, PathStatusResponse, ReadEditableTextResponse, ReadResponse, RenameResponse, WriteTextResponse};
use crate::commands::git::{GitBranchesResponse, GitCloneTask, GitCloneTaskRegistry, GitCommitDetailsResponse, GitDiffResponse, GitLogResponse, GitOperationResponse, GitRemoteBranchesResponse, GitRepositoryDiscovery, GitRepositoryState};
use crate::commands::hook::{HookHttpRunResponse, HookScopeRegistry};
use crate::commands::mcp::{McpCallToolResponse, McpRuntimeManager, McpRuntimeStatus, McpRuntimeTestResponse, McpServerConfig, McpStopServerResponse, McpToolInfo};
use crate::commands::settings::{CcsProvidersResponse, CherryProvidersResponse, SettingsLoadResponse, SshKnownHostResetResponse, SshPatchApplyResponse};
use crate::commands::shell::{ShellCancelResponse};
use crate::commands::subagent_store::{SubagentIdentityListInput, SubagentIdentityRecord, SubagentIdentityUpsertInput, SubagentMessageAppendInput, SubagentMessageListInput, SubagentMessageRecord, SubagentPruneResult, SubagentRunListInput, SubagentRunLoadInput, SubagentRunPruneInput, SubagentRunRecord, SubagentRunSaveInput, SubagentRunStateRecord};
use crate::commands::subagent_worktree::{SubagentWorktreeApplyInput, SubagentWorktreeApplyResponse, SubagentWorktreeCleanupInput, SubagentWorktreeCleanupItem, SubagentWorktreeCreateInput, SubagentWorktreeCreateResponse, SubagentWorktreeStatusInput, SubagentWorktreeStatusResponse};
use crate::commands::system::{SystemCreateProjectFolderResponse, SystemPastedTextInput, SystemPickReadableFilesResponse, SystemUploadedImagePreviewResponse, SystemUploadedNativeAttachmentResponse, SystemUploadedReadableFileInput};
use crate::commands::update::{AppUpdateCheckResponse};
use crate::runtime::managed_process::{ManagedProcessLogResponse, ManagedProcessRegistry, ManagedProcessSnapshot, ManagedProcessStartResponse, ManagedProcessStatusResponse, ManagedProcessStopResponse};
use crate::runtime::sftp::{SftpActionResponse, SftpListResponse, SftpReadTextResponse, SftpSessionRegistry, SftpStatResponse, SftpTransferResponse};
use crate::runtime::shell_runner::{ShellRunRegistry, ShellRunResponse};
use crate::runtime::task_runner::{HttpRequestInput};
use crate::runtime::terminal::{SshLocalForwardActionResponse, SshLocalForwardListResponse, SshTerminalTabsSnapshot, TerminalListResponse, TerminalReadTailResponse, TerminalSessionRecord, TerminalSessionRegistry, TerminalShellOptionsResponse, TerminalSnapshotResponse, TerminalSshCreateResponse, TerminalSshExecResponse, TerminalSshLatencyResponse, TerminalStreamSnapshotResponse};
use crate::services::automation::{AutomationApplyInput, AutomationSnapshot, CompletePromptRunInput, CronApplyResponse, CronRunNowResponse, CronRunRecord, HooksApplyResponse, PromptCompletionResponse, PromptRunRequest};
use crate::services::automation::scheduler::{AutomationScheduler};
use crate::services::automation::store::{AutomationStore};
use crate::services::gateway::{GatewayChatClaimedRequest, GatewayChatQueueEventInput, GatewayChatQueueResponseInput, GatewayController, GatewayStatusSnapshot};
use crate::services::gateway::chat_ingress::{GatewayChatCheckpointCommitResult, GatewayChatCheckpointInput, GatewayChatIngressAcceptResult, GatewayChatIngressBatchInput};
use crate::services::memory::{MemoryAcceptArgs, MemoryBatchArgs, MemoryBatchResponse, MemoryDeleteArgs, MemoryDeleteProjectArgs, MemoryDeleteProjectResponse, MemoryListArgs, MemoryListResponse, MemoryMutationResponse, MemoryOrganizeDueClaimArgs, MemoryOrganizeDueClaimResponse, MemoryOrganizeRun, MemoryOrganizeRunClearHistoryResponse, MemoryOrganizeRunCreateArgs, MemoryOrganizeRunCreateResponse, MemoryOrganizeRunListArgs, MemoryOrganizeRunListResponse, MemoryOrganizeRunReadArgs, MemoryOrganizeRunUpdateArgs, MemoryOverviewResponse, MemoryPathsInfo, MemoryQuotaSummaryArgs, MemoryQuotaSummaryResponse, MemoryReadArgs, MemoryReadResponse, MemoryRecentRejectionsArgs, MemoryRecentRejectionsResponse, MemorySearchArgs, MemorySearchResponse, MemoryStore, MemoryUpdateArgs, MemoryWriteArgs};
use crate::services::power_activity::{PowerActivityManager};
use crate::services::provider_usage::{ProviderUsageResult, ProviderUsageService};
use crate::services::proxy::{ProxyServerInfo, ProxyServerState};
use crate::services::skills::{SystemListSkillFilesResponse, SystemManageSkillResponse, SystemReadSkillMetadataResponse, SystemReadSkillTextResponse};
use crate::services::tray::{TrayMenuHandles, TrayMenuModel};
use crate::services::tunnel::{GatewayTunnelCreateInput, GatewayTunnelUpdateInput, TunnelStatePayload};

use std::sync::atomic::AtomicBool;
use std::collections::HashMap;

// ===== app =====
#[tauri::command]
pub fn app_window_pinned(
    pin_state: tauri::State<'_, Arc<WindowPinState>>,
) -> bool {
    crate::commands::app::app_window_pinned(pin_state.inner())
}

#[tauri::command]
pub fn app_toggle_window_pin(
    app: tauri::AppHandle,
) {
    crate::commands::app::app_toggle_window_pin(app)
}

#[tauri::command]
pub fn app_set_global_shortcuts(
    app: tauri::AppHandle,
    bindings: Vec<GlobalShortcutBinding>,
    registry: tauri::State<'_, Arc<GlobalShortcutRegistry>>,
) -> Result<Vec<GlobalShortcutFailure>, String> {
    crate::commands::app::app_set_global_shortcuts(app, bindings, registry.inner())
}

#[tauri::command]
pub fn app_runtime_platform(
) -> RuntimePlatformResponse {
    crate::commands::app::app_runtime_platform()
}

#[tauri::command]
pub fn app_set_close_window_behavior(
    behavior: String,
    close_window_behavior: tauri::State<'_, Arc<CloseWindowBehaviorState>>,
) -> Result<(), String> {
    crate::commands::app::app_set_close_window_behavior(behavior, close_window_behavior.inner())
}

#[tauri::command]
pub fn app_confirmed_exit(
    app: tauri::AppHandle,
    allow_exit: tauri::State<'_, Arc<AtomicBool>>,
    terminal_registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
) -> Result<(), String> {
    crate::commands::app::app_confirmed_exit(app, allow_exit.inner(), terminal_registry.inner())
}

#[tauri::command]
pub async fn app_macos_traffic_light_metrics(
    window: tauri::Window,
) -> Result<Option<MacOsTrafficLightMetrics>, String> {
    crate::commands::app::app_macos_traffic_light_metrics(window).await
}

// ===== tray =====
#[tauri::command(rename_all = "snake_case")]
pub async fn app_tray_menu_sync(
    app: tauri::AppHandle,
    model: TrayMenuModel,
    handles: tauri::State<'_, Arc<TrayMenuHandles>>,
) -> Result<(), String> {
    crate::commands::tray::app_tray_menu_sync(app, model, handles.inner()).await
}

// ===== update =====
#[tauri::command(rename_all = "snake_case")]
pub async fn app_update_check(
    app: tauri::AppHandle,
    include_prerelease: bool,
) -> Result<AppUpdateCheckResponse, String> {
    crate::commands::update::app_update_check(app, include_prerelease).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn app_update_install(
    app: tauri::AppHandle,
    include_prerelease: bool,
) -> Result<AppUpdateCheckResponse, String> {
    crate::commands::update::app_update_install(app, include_prerelease).await
}

#[tauri::command]
pub fn app_restart(
    app: tauri::AppHandle,
) -> Result<(), String> {
    crate::commands::update::app_restart(app)
}

// ===== system =====
#[tauri::command(rename_all = "snake_case")]
pub async fn system_pick_folder(
    initial_workdir: Option<String>,
) -> Result<Option<String>, String> {
    crate::commands::system::system_pick_folder(initial_workdir).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn system_pick_file(
    initial_workdir: Option<String>,
    filter_name: Option<String>,
    extensions: Option<Vec<String>>,
) -> Result<Option<String>, String> {
    crate::commands::system::system_pick_file(initial_workdir, filter_name, extensions).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn system_create_project_folder(
    parent: String,
    name: String,
) -> Result<SystemCreateProjectFolderResponse, String> {
    crate::commands::system::system_create_project_folder(parent, name).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn system_pick_readable_files(
    workdir: String,
    max_files: Option<usize>,
) -> Result<SystemPickReadableFilesResponse, String> {
    crate::commands::system::system_pick_readable_files(workdir, max_files).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn system_import_readable_file_paths(
    workdir: String,
    paths: Vec<String>,
    max_files: Option<usize>,
) -> Result<SystemPickReadableFilesResponse, String> {
    crate::commands::system::system_import_readable_file_paths(workdir, paths, max_files).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn system_import_uploaded_readable_files(
    workdir: String,
    files: Vec<SystemUploadedReadableFileInput>,
    max_files: Option<usize>,
) -> Result<SystemPickReadableFilesResponse, String> {
    crate::commands::system::system_import_uploaded_readable_files(workdir, files, max_files).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn system_import_pasted_texts(
    workdir: String,
    texts: Vec<SystemPastedTextInput>,
) -> Result<SystemPickReadableFilesResponse, String> {
    crate::commands::system::system_import_pasted_texts(workdir, texts).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn system_read_uploaded_image_preview(
    workdir: String,
    absolute_path: String,
) -> Result<SystemUploadedImagePreviewResponse, String> {
    crate::commands::system::system_read_uploaded_image_preview(workdir, absolute_path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn system_read_uploaded_native_attachment(
    workdir: String,
    absolute_path: Option<String>,
    kind: Option<String>,
) -> Result<SystemUploadedNativeAttachmentResponse, String> {
    crate::commands::system::system_read_uploaded_native_attachment(workdir, absolute_path, kind).await
}

#[tauri::command]
pub async fn system_list_skill_files(
) -> Result<SystemListSkillFilesResponse, String> {
    crate::commands::system::system_list_skill_files().await
}

#[tauri::command]
pub async fn system_ensure_builtin_skills(
) -> Result<Vec<crate::services::skills::SystemBuiltinSkillSeedResponse>, String> {
    crate::commands::system::system_ensure_builtin_skills().await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn system_manage_skill(
    payload: Value,
) -> Result<SystemManageSkillResponse, String> {
    crate::commands::system::system_manage_skill(payload).await
}

#[tauri::command]
pub async fn system_read_skill_text(
    path: String,
    offset: Option<usize>,
    length: Option<usize>,
) -> Result<SystemReadSkillTextResponse, String> {
    crate::commands::system::system_read_skill_text(path, offset, length).await
}

#[tauri::command]
pub async fn system_read_skill_metadata(
    path: String,
) -> Result<SystemReadSkillMetadataResponse, String> {
    crate::commands::system::system_read_skill_metadata(path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn system_append_debug_jsonl(
    conversation_id: String,
    entry: Value,
) -> Result<(), String> {
    crate::commands::system::system_append_debug_jsonl(conversation_id, entry).await
}

#[tauri::command]
pub async fn system_clipboard_read_text(
) -> Result<String, String> {
    crate::commands::system::system_clipboard_read_text().await
}

#[tauri::command(rename_all = "snake_case")]
pub fn system_begin_power_activity(
    activity_id: String,
    reason: String,
    ttl_ms: Option<u64>,
    power_activity: tauri::State<'_, Arc<PowerActivityManager>>,
) -> Result<(), String> {
    crate::commands::system::system_begin_power_activity(activity_id, reason, ttl_ms, power_activity.inner())
}

#[tauri::command(rename_all = "snake_case")]
pub fn system_end_power_activity(
    activity_id: String,
    power_activity: tauri::State<'_, Arc<PowerActivityManager>>,
) -> Result<(), String> {
    crate::commands::system::system_end_power_activity(activity_id, power_activity.inner())
}

// ===== cron =====
#[tauri::command(rename_all = "snake_case")]
pub async fn cron_validate_expression(
    expression: String,
) -> Result<(), String> {
    crate::commands::cron::cron_validate_expression(expression).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn automation_snapshot(
    store: tauri::State<'_, Arc<AutomationStore>>,
) -> Result<AutomationSnapshot, String> {
    crate::commands::cron::automation_snapshot(store.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn automation_cron_apply(
    input: AutomationApplyInput,
    store: tauri::State<'_, Arc<AutomationStore>>,
) -> Result<CronApplyResponse, String> {
    crate::commands::cron::automation_cron_apply(input, store.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn automation_hooks_apply(
    input: AutomationApplyInput,
    store: tauri::State<'_, Arc<AutomationStore>>,
) -> Result<HooksApplyResponse, String> {
    crate::commands::cron::automation_hooks_apply(input, store.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn automation_list_runs(
    task_id: String,
    limit: Option<usize>,
    store: tauri::State<'_, Arc<AutomationStore>>,
) -> Result<Vec<CronRunRecord>, String> {
    crate::commands::cron::automation_list_runs(task_id, limit, store.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn automation_clear_runs(
    task_id: String,
    store: tauri::State<'_, Arc<AutomationStore>>,
) -> Result<usize, String> {
    crate::commands::cron::automation_clear_runs(task_id, store.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn automation_run_cron_now(
    task_id: String,
    store: tauri::State<'_, Arc<AutomationStore>>,
) -> Result<CronRunNowResponse, String> {
    crate::commands::cron::automation_run_cron_now(task_id, store.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn automation_claim_prompt_runs(
    store: tauri::State<'_, Arc<AutomationStore>>,
) -> Result<Vec<PromptRunRequest>, String> {
    crate::commands::cron::automation_claim_prompt_runs(store.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn automation_release_prompt_run(
    execution_id: String,
    store: tauri::State<'_, Arc<AutomationStore>>,
) -> Result<(), String> {
    crate::commands::cron::automation_release_prompt_run(execution_id, store.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn automation_complete_prompt_run(
    input: CompletePromptRunInput,
    store: tauri::State<'_, Arc<AutomationStore>>,
) -> Result<PromptCompletionResponse, String> {
    crate::commands::cron::automation_complete_prompt_run(input, store.inner()).await
}

// ===== hook =====
#[tauri::command(rename_all = "snake_case")]
pub async fn hook_run_script(
    workdir: Option<String>,
    script: String,
    timeout_ms: Option<u64>,
    scope_id: Option<String>,
    context: Option<HashMap<String, String>>,
    registry: tauri::State<'_, Arc<HookScopeRegistry>>,
) -> Result<ShellRunResponse, String> {
    crate::commands::hook::hook_run_script(workdir, script, timeout_ms, scope_id, context, registry.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn hook_run_http_requests(
    requests: Vec<HttpRequestInput>,
    scope_id: Option<String>,
    registry: tauri::State<'_, Arc<HookScopeRegistry>>,
) -> Result<HookHttpRunResponse, String> {
    crate::commands::hook::hook_run_http_requests(requests, scope_id, registry.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn hook_cancel_scope(
    scope_id: String,
    registry: tauri::State<'_, Arc<HookScopeRegistry>>,
) -> Result<(), String> {
    crate::commands::hook::hook_cancel_scope(scope_id, registry.inner()).await
}

// ===== settings =====
#[tauri::command]
pub async fn settings_list_ccswitch_providers(
) -> Result<CcsProvidersResponse, String> {
    crate::commands::settings::settings_list_ccswitch_providers().await
}

#[tauri::command]
pub async fn settings_list_cherry_studio_providers(
) -> Result<CherryProvidersResponse, String> {
    crate::commands::settings::settings_list_cherry_studio_providers().await
}

#[tauri::command]
pub async fn settings_list_cherry_studio_providers_from_path(
    data_path: String,
) -> Result<CherryProvidersResponse, String> {
    crate::commands::settings::settings_list_cherry_studio_providers_from_path(data_path).await
}

#[tauri::command]
pub async fn settings_load_all(
) -> Result<SettingsLoadResponse, String> {
    crate::commands::settings::settings_load_all().await
}

#[tauri::command]
pub async fn settings_save_providers(
    payload: Value,
) -> Result<(), String> {
    crate::commands::settings::settings_save_providers(payload).await
}

#[tauri::command]
pub async fn settings_save_system(
    payload: Value,
    automation_scheduler: tauri::State<'_, Arc<AutomationScheduler>>,
) -> Result<(), String> {
    crate::commands::settings::settings_save_system(payload, automation_scheduler.inner()).await
}

#[tauri::command]
pub async fn settings_save_mcp(
    payload: Value,
) -> Result<(), String> {
    crate::commands::settings::settings_save_mcp(payload).await
}

#[tauri::command]
pub async fn settings_save_remote(
    payload: Value,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::settings::settings_save_remote(payload, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn settings_save_memory(
    payload: Value,
) -> Result<(), String> {
    crate::commands::settings::settings_save_memory(payload).await
}

#[tauri::command]
pub async fn settings_save_agents(
    payload: Value,
) -> Result<(), String> {
    crate::commands::settings::settings_save_agents(payload).await
}

#[tauri::command]
pub async fn settings_save_ssh(
    payload: Value,
) -> Result<(), String> {
    crate::commands::settings::settings_save_ssh(payload).await
}

#[tauri::command]
pub async fn settings_apply_ssh_patch(
    payload: Value,
) -> Result<SshPatchApplyResponse, String> {
    crate::commands::settings::settings_apply_ssh_patch(payload).await
}

#[tauri::command]
pub async fn settings_reset_ssh_known_host(
    host: String,
    port: u16,
) -> Result<SshKnownHostResetResponse, String> {
    crate::commands::settings::settings_reset_ssh_known_host(host, port).await
}

// ===== subagent_store =====
#[tauri::command]
pub async fn subagent_identity_upsert(
    input: SubagentIdentityUpsertInput,
) -> Result<SubagentIdentityRecord, String> {
    crate::commands::subagent_store::subagent_identity_upsert(input).await
}

#[tauri::command]
pub async fn subagent_identity_list(
    input: SubagentIdentityListInput,
) -> Result<Vec<SubagentIdentityRecord>, String> {
    crate::commands::subagent_store::subagent_identity_list(input).await
}

#[tauri::command]
pub async fn subagent_run_save(
    input: SubagentRunSaveInput,
) -> Result<(), String> {
    crate::commands::subagent_store::subagent_run_save(input).await
}

#[tauri::command]
pub async fn subagent_run_list(
    input: SubagentRunListInput,
) -> Result<Vec<SubagentRunRecord>, String> {
    crate::commands::subagent_store::subagent_run_list(input).await
}

#[tauri::command]
pub async fn subagent_run_load(
    input: SubagentRunLoadInput,
) -> Result<Option<SubagentRunStateRecord>, String> {
    crate::commands::subagent_store::subagent_run_load(input).await
}

#[tauri::command]
pub async fn subagent_run_prune(
    input: SubagentRunPruneInput,
) -> Result<SubagentPruneResult, String> {
    crate::commands::subagent_store::subagent_run_prune(input).await
}

#[tauri::command]
pub async fn subagent_message_append(
    input: SubagentMessageAppendInput,
) -> Result<SubagentMessageRecord, String> {
    crate::commands::subagent_store::subagent_message_append(input).await
}

#[tauri::command]
pub async fn subagent_message_list(
    input: SubagentMessageListInput,
) -> Result<Vec<SubagentMessageRecord>, String> {
    crate::commands::subagent_store::subagent_message_list(input).await
}

// ===== chat_history =====
#[tauri::command]
pub async fn chat_history_branch(
    id: String,
    base_message_ref: ChatHistoryMessageRef,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<ChatHistorySummary, String> {
    crate::commands::chat_history::chat_history_branch(id, base_message_ref, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn chat_history_list(
    page: i64,
    page_size: i64,
    cwd: Option<String>,
    cwd_empty: Option<bool>,
) -> Result<ChatHistoryListResponse, String> {
    crate::commands::chat_history::chat_history_list(page, page_size, cwd, cwd_empty).await
}

#[tauri::command]
pub async fn chat_history_workdirs(
) -> Result<ChatHistoryWorkdirsResponse, String> {
    crate::commands::chat_history::chat_history_workdirs().await
}

#[tauri::command]
pub async fn chat_history_shared_list(
    page: i64,
    page_size: i64,
) -> Result<ChatHistoryListResponse, String> {
    crate::commands::chat_history::chat_history_shared_list(page, page_size).await
}

#[tauri::command]
pub async fn chat_history_search(
    args: ChatHistorySearchArgs,
) -> Result<ChatHistorySearchResponse, String> {
    crate::commands::chat_history::chat_history_search(args).await
}

#[tauri::command]
pub async fn chat_history_get_window(
    id: String,
    max_messages: i64,
    before_offset: Option<i64>,
    expected_revision: Option<String>,
    include_active_segment: bool,
) -> Result<ChatHistoryWindowRecord, String> {
    crate::commands::chat_history::chat_history_get_window(id, max_messages, before_offset, expected_revision, include_active_segment).await
}

#[tauri::command]
pub async fn chat_history_upsert(
    input: ChatHistoryUpsertInput,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<ChatHistorySummary, String> {
    crate::commands::chat_history::chat_history_upsert(input, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn chat_history_upsert_active_segment(
    input: ChatHistorySegmentMutationInput,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<ChatHistorySummary, String> {
    crate::commands::chat_history::chat_history_upsert_active_segment(input, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn chat_history_append_segment(
    input: ChatHistorySegmentMutationInput,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<ChatHistorySummary, String> {
    crate::commands::chat_history::chat_history_append_segment(input, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn chat_history_rename(
    id: String,
    title: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<ChatHistorySummary, String> {
    crate::commands::chat_history::chat_history_rename(id, title, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn chat_history_set_pinned(
    id: String,
    is_pinned: bool,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<ChatHistorySummary, String> {
    crate::commands::chat_history::chat_history_set_pinned(id, is_pinned, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn chat_history_set_model(
    id: String,
    selected_model_json: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<ChatHistorySummary, String> {
    crate::commands::chat_history::chat_history_set_model(id, selected_model_json, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn chat_history_share_get(
    id: String,
) -> Result<ChatHistoryShareStatus, String> {
    crate::commands::chat_history::chat_history_share_get(id).await
}

#[tauri::command]
pub async fn chat_history_share_set(
    id: String,
    enabled: bool,
    redact_tool_content: Option<bool>,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<ChatHistoryShareStatus, String> {
    crate::commands::chat_history::chat_history_share_set(id, enabled, redact_tool_content, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn chat_history_delete(
    id: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::chat_history::chat_history_delete(id, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn chat_history_replace_from_message(
    id: String,
    base_message_ref: ChatHistoryMessageRef,
    replacement_message: Value,
    max_messages: i64,
    expected_revision: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<ChatHistoryWindowRecord, String> {
    crate::commands::chat_history::chat_history_replace_from_message(id, base_message_ref, replacement_message, max_messages, expected_revision, gateway_controller.inner()).await
}

// ===== gateway =====
#[tauri::command]
pub async fn provider_usage_query(
    provider_id: String,
    refresh: bool,
    provider_usage_service: tauri::State<'_, Arc<ProviderUsageService>>,
) -> Result<ProviderUsageResult, String> {
    crate::commands::gateway::provider_usage_query(provider_id, refresh, provider_usage_service.inner()).await
}

#[tauri::command]
pub async fn provider_usage_test(
    provider_id: String,
    config_json: String,
    provider_usage_service: tauri::State<'_, Arc<ProviderUsageService>>,
) -> Result<ProviderUsageResult, String> {
    crate::commands::gateway::provider_usage_test(provider_id, config_json, provider_usage_service.inner()).await
}

#[tauri::command]
pub async fn gateway_connect(
    payload: Option<Value>,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_connect(payload, gateway_controller.inner()).await
}

#[tauri::command]
pub fn gateway_disconnect(
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_disconnect(gateway_controller.inner())
}

#[tauri::command]
pub fn gateway_status(
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<GatewayStatusSnapshot, String> {
    crate::commands::gateway::gateway_status(gateway_controller.inner())
}

#[tauri::command(rename_all = "snake_case")]
pub fn gateway_nudge_connection(
    reason: Option<String>,
    force_reconnect: Option<bool>,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<bool, String> {
    crate::commands::gateway::gateway_nudge_connection(reason, force_reconnect, gateway_controller.inner())
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_send_chat_ingress_batch(
    input: GatewayChatIngressBatchInput,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<GatewayChatIngressAcceptResult, String> {
    crate::commands::gateway::gateway_send_chat_ingress_batch(input, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_commit_chat_checkpoint(
    input: GatewayChatCheckpointInput,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<GatewayChatCheckpointCommitResult, String> {
    crate::commands::gateway::gateway_commit_chat_checkpoint(input, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_chat_claim_next(
    worker_id: String,
    lease_ms: Option<u64>,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<Option<GatewayChatClaimedRequest>, String> {
    crate::commands::gateway::gateway_chat_claim_next(worker_id, lease_ms, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_chat_mark_started(
    request_id: String,
    conversation_id: String,
    worker_id: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_chat_mark_started(request_id, conversation_id, worker_id, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_chat_mark_local_started(
    request_id: String,
    conversation_id: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_chat_mark_local_started(request_id, conversation_id, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_chat_mark_local_cancelled(
    request_id: String,
    conversation_id: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_chat_mark_local_cancelled(request_id, conversation_id, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_chat_mark_queued_in_gui(
    request_id: String,
    conversation_id: String,
    worker_id: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_chat_mark_queued_in_gui(request_id, conversation_id, worker_id, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_chat_complete(
    request_id: String,
    conversation_id: String,
    worker_id: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_chat_complete(request_id, conversation_id, worker_id, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_chat_fail(
    request_id: String,
    conversation_id: Option<String>,
    error_code: String,
    message: String,
    terminal: bool,
    worker_id: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_chat_fail(request_id, conversation_id, error_code, message, terminal, worker_id, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_chat_cancel_request(
    request_id: String,
    conversation_id: String,
    worker_id: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_chat_cancel_request(request_id, conversation_id, worker_id, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub fn gateway_chat_heartbeat(
    request_id: String,
    worker_id: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_chat_heartbeat(request_id, worker_id, gateway_controller.inner())
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_chat_runtime_heartbeat(
    worker_id: String,
    state: String,
    visible: bool,
    active_run_count: u32,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_chat_runtime_heartbeat(worker_id, state, visible, active_run_count, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub fn gateway_chat_release_lease(
    request_id: String,
    worker_id: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_chat_release_lease(request_id, worker_id, gateway_controller.inner())
}

#[tauri::command(rename_all = "snake_case")]
pub fn gateway_chat_queue_respond(
    input: GatewayChatQueueResponseInput,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_chat_queue_respond(input, gateway_controller.inner())
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_publish_chat_queue_event(
    input: GatewayChatQueueEventInput,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_publish_chat_queue_event(input, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn gateway_publish_settings_sync(
    payload: Value,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_publish_settings_sync(payload, gateway_controller.inner()).await
}

#[tauri::command]
pub fn gateway_tunnel_state(
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<TunnelStatePayload, String> {
    crate::commands::gateway::gateway_tunnel_state(gateway_controller.inner())
}

#[tauri::command]
pub async fn gateway_tunnel_create(
    input: GatewayTunnelCreateInput,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_tunnel_create(input, gateway_controller.inner()).await
}

#[tauri::command]
pub async fn gateway_tunnel_update(
    input: GatewayTunnelUpdateInput,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_tunnel_update(input, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_tunnel_close(
    tunnel_id: String,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_tunnel_close(tunnel_id, gateway_controller.inner()).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn gateway_tunnel_check(
    tunnel_id: Option<String>,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::gateway_tunnel_check(tunnel_id, gateway_controller.inner()).await
}

#[tauri::command]
pub fn workspace_watch_set(
    workdirs: Vec<String>,
    gateway_controller: tauri::State<'_, Arc<GatewayController>>,
) -> Result<(), String> {
    crate::commands::gateway::workspace_watch_set(workdirs, gateway_controller.inner())
}

// ===== mcp =====
#[tauri::command(rename_all = "snake_case")]
pub async fn mcp_list_tools(
    state: tauri::State<'_, Arc<McpRuntimeManager>>,
    servers: Vec<McpServerConfig>,
) -> Result<Vec<McpToolInfo>, String> {
    crate::commands::mcp::mcp_list_tools(state.inner(), servers).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn mcp_call_tool(
    state: tauri::State<'_, Arc<McpRuntimeManager>>,
    run_registry: tauri::State<'_, Arc<ShellRunRegistry>>,
    server_id: String,
    tool_name: String,
    arguments: Value,
    run_id: Option<String>,
) -> Result<McpCallToolResponse, String> {
    crate::commands::mcp::mcp_call_tool(state.inner(), run_registry.inner(), server_id, tool_name, arguments, run_id).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn mcp_runtime_status(
    state: tauri::State<'_, Arc<McpRuntimeManager>>,
    server_id: String,
) -> Result<McpRuntimeStatus, String> {
    crate::commands::mcp::mcp_runtime_status(state.inner(), server_id).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn mcp_stop_server(
    state: tauri::State<'_, Arc<McpRuntimeManager>>,
    server_id: String,
) -> Result<McpStopServerResponse, String> {
    crate::commands::mcp::mcp_stop_server(state.inner(), server_id).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn mcp_test_server(
    state: tauri::State<'_, Arc<McpRuntimeManager>>,
    server: McpServerConfig,
    include_schema: Option<bool>,
    persist: Option<bool>,
) -> Result<McpRuntimeTestResponse, String> {
    crate::commands::mcp::mcp_test_server(state.inner(), server, include_schema, persist).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn mcp_restart_server(
    state: tauri::State<'_, Arc<McpRuntimeManager>>,
    server: McpServerConfig,
    include_schema: Option<bool>,
    persist: Option<bool>,
) -> Result<McpRuntimeTestResponse, String> {
    crate::commands::mcp::mcp_restart_server(state.inner(), server, include_schema, persist).await
}

// ===== memory =====
#[tauri::command]
pub async fn memory_list(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryListArgs,
) -> Result<MemoryListResponse, String> {
    crate::commands::memory::memory_list(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_read(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryReadArgs,
) -> Result<MemoryReadResponse, String> {
    crate::commands::memory::memory_read(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_search(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemorySearchArgs,
) -> Result<MemorySearchResponse, String> {
    crate::commands::memory::memory_search(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_write(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryWriteArgs,
) -> Result<MemoryMutationResponse, String> {
    crate::commands::memory::memory_write(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_update(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryUpdateArgs,
) -> Result<MemoryMutationResponse, String> {
    crate::commands::memory::memory_update(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_delete(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryDeleteArgs,
) -> Result<MemoryMutationResponse, String> {
    crate::commands::memory::memory_delete(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_delete_project(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryDeleteProjectArgs,
) -> Result<MemoryDeleteProjectResponse, String> {
    crate::commands::memory::memory_delete_project(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_accept(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryAcceptArgs,
) -> Result<MemoryMutationResponse, String> {
    crate::commands::memory::memory_accept(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_apply_batch(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryBatchArgs,
) -> Result<MemoryBatchResponse, String> {
    crate::commands::memory::memory_apply_batch(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_organize_run_create(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryOrganizeRunCreateArgs,
) -> Result<MemoryOrganizeRunCreateResponse, String> {
    crate::commands::memory::memory_organize_run_create(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_organize_run_update(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryOrganizeRunUpdateArgs,
) -> Result<Option<MemoryOrganizeRun>, String> {
    crate::commands::memory::memory_organize_run_update(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_organize_run_list(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: Option<MemoryOrganizeRunListArgs>,
) -> Result<MemoryOrganizeRunListResponse, String> {
    crate::commands::memory::memory_organize_run_list(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_organize_run_read(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryOrganizeRunReadArgs,
) -> Result<Option<MemoryOrganizeRun>, String> {
    crate::commands::memory::memory_organize_run_read(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_organize_run_clear_history(
    state: tauri::State<'_, Arc<MemoryStore>>,
) -> Result<MemoryOrganizeRunClearHistoryResponse, String> {
    crate::commands::memory::memory_organize_run_clear_history(state.inner()).await
}

#[tauri::command]
pub async fn memory_organize_due_claim(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryOrganizeDueClaimArgs,
) -> Result<MemoryOrganizeDueClaimResponse, String> {
    crate::commands::memory::memory_organize_due_claim(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_organize_due_complete(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: MemoryOrganizeRunUpdateArgs,
) -> Result<Option<MemoryOrganizeRun>, String> {
    crate::commands::memory::memory_organize_due_complete(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_index_overview(
    state: tauri::State<'_, Arc<MemoryStore>>,
    workdir: Option<String>,
) -> Result<MemoryOverviewResponse, String> {
    crate::commands::memory::memory_index_overview(state.inner(), workdir).await
}

#[tauri::command]
pub async fn memory_paths_info(
    state: tauri::State<'_, Arc<MemoryStore>>,
) -> Result<MemoryPathsInfo, String> {
    crate::commands::memory::memory_paths_info(state.inner()).await
}

#[tauri::command]
pub async fn memory_recent_rejections(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: Option<MemoryRecentRejectionsArgs>,
) -> Result<MemoryRecentRejectionsResponse, String> {
    crate::commands::memory::memory_recent_rejections(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_today_local_date(
    state: tauri::State<'_, Arc<MemoryStore>>,
    rollover_hour: Option<u32>,
) -> Result<String, String> {
    crate::commands::memory::memory_today_local_date(state.inner(), rollover_hour).await
}

#[tauri::command]
pub async fn memory_today_daily(
    state: tauri::State<'_, Arc<MemoryStore>>,
    rollover_hour: Option<u32>,
) -> Result<Option<MemoryReadResponse>, String> {
    crate::commands::memory::memory_today_daily(state.inner(), rollover_hour).await
}

#[tauri::command]
pub async fn memory_quota_summary(
    state: tauri::State<'_, Arc<MemoryStore>>,
    args: Option<MemoryQuotaSummaryArgs>,
) -> Result<MemoryQuotaSummaryResponse, String> {
    crate::commands::memory::memory_quota_summary(state.inner(), args).await
}

#[tauri::command]
pub async fn memory_wipe_all(
    state: tauri::State<'_, Arc<MemoryStore>>,
) -> Result<MemoryPathsInfo, String> {
    crate::commands::memory::memory_wipe_all(state.inner()).await
}

// ===== process =====
#[tauri::command(rename_all = "snake_case")]
pub fn managed_process_start(
    registry: tauri::State<'_, Arc<ManagedProcessRegistry>>,
    workdir: String,
    command: String,
    cwd: Option<String>,
    label: Option<String>,
    isolated: Option<bool>,
) -> Result<ManagedProcessStartResponse, String> {
    crate::commands::process::managed_process_start(registry.inner(), workdir, command, cwd, label, isolated)
}

#[tauri::command(rename_all = "snake_case")]
pub fn managed_process_status(
    registry: tauri::State<'_, Arc<ManagedProcessRegistry>>,
    process_id: Option<String>,
) -> Result<ManagedProcessStatusResponse, String> {
    crate::commands::process::managed_process_status(registry.inner(), process_id)
}

#[tauri::command(rename_all = "snake_case")]
pub fn managed_process_stop(
    registry: tauri::State<'_, Arc<ManagedProcessRegistry>>,
    process_id: String,
) -> Result<ManagedProcessStopResponse, String> {
    crate::commands::process::managed_process_stop(registry.inner(), process_id)
}

#[tauri::command(rename_all = "snake_case")]
pub fn managed_process_read_log(
    registry: tauri::State<'_, Arc<ManagedProcessRegistry>>,
    process_id: String,
    max_bytes: Option<u64>,
) -> Result<ManagedProcessLogResponse, String> {
    crate::commands::process::managed_process_read_log(registry.inner(), process_id, max_bytes)
}

#[tauri::command(rename_all = "snake_case")]
pub fn managed_process_snapshot(
    registry: tauri::State<'_, Arc<ManagedProcessRegistry>>,
) -> Result<ManagedProcessSnapshot, String> {
    crate::commands::process::managed_process_snapshot(registry.inner())
}

#[tauri::command(rename_all = "snake_case")]
pub fn managed_process_clear(
    registry: tauri::State<'_, Arc<ManagedProcessRegistry>>,
    process_id: Option<String>,
) -> Result<ManagedProcessSnapshot, String> {
    crate::commands::process::managed_process_clear(registry.inner(), process_id)
}

// ===== sftp =====
#[tauri::command(rename_all = "snake_case")]
pub async fn sftp_list(
    registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    session_id: String,
    project_path_key: Option<String>,
    workdir: String,
    side: String,
    path: Option<String>,
) -> Result<SftpListResponse, String> {
    crate::commands::sftp::sftp_list(registry.inner(), session_id, project_path_key, workdir, side, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn sftp_stat(
    registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    session_id: String,
    project_path_key: Option<String>,
    workdir: String,
    side: String,
    path: Option<String>,
) -> Result<SftpStatResponse, String> {
    crate::commands::sftp::sftp_stat(registry.inner(), session_id, project_path_key, workdir, side, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn sftp_read_text(
    registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    session_id: String,
    project_path_key: Option<String>,
    path: String,
    offset: Option<u64>,
    max_bytes: Option<usize>,
) -> Result<SftpReadTextResponse, String> {
    crate::commands::sftp::sftp_read_text(registry.inner(), session_id, project_path_key, path, offset, max_bytes).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn sftp_write_text(
    registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    session_id: String,
    project_path_key: Option<String>,
    path: String,
    content: String,
    overwrite: Option<bool>,
    create_parent_dirs: Option<bool>,
) -> Result<SftpActionResponse, String> {
    crate::commands::sftp::sftp_write_text(registry.inner(), session_id, project_path_key, path, content, overwrite, create_parent_dirs).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn sftp_mkdir(
    registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    session_id: String,
    project_path_key: Option<String>,
    workdir: String,
    side: String,
    path: String,
) -> Result<SftpActionResponse, String> {
    crate::commands::sftp::sftp_mkdir(registry.inner(), session_id, project_path_key, workdir, side, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn sftp_rename(
    registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    session_id: String,
    project_path_key: Option<String>,
    workdir: String,
    side: String,
    from_path: String,
    to_path: String,
) -> Result<SftpActionResponse, String> {
    crate::commands::sftp::sftp_rename(registry.inner(), session_id, project_path_key, workdir, side, from_path, to_path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn sftp_delete(
    registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    session_id: String,
    project_path_key: Option<String>,
    workdir: String,
    side: String,
    path: String,
    recursive: Option<bool>,
) -> Result<SftpActionResponse, String> {
    crate::commands::sftp::sftp_delete(registry.inner(), session_id, project_path_key, workdir, side, path, recursive).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn sftp_transfer(
    registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    session_id: String,
    project_path_key: Option<String>,
    workdir: String,
    direction: String,
    source_path: String,
    target_path: String,
    recursive: Option<bool>,
    overwrite: Option<bool>,
) -> Result<SftpTransferResponse, String> {
    crate::commands::sftp::sftp_transfer(registry.inner(), session_id, project_path_key, workdir, direction, source_path, target_path, recursive, overwrite).await
}

#[tauri::command(rename_all = "snake_case")]
pub fn sftp_cancel_transfer(
    registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    session_id: String,
    transfer_id: String,
) -> Result<(), String> {
    crate::commands::sftp::sftp_cancel_transfer(registry.inner(), session_id, transfer_id)
}

#[tauri::command(rename_all = "snake_case")]
pub fn sftp_transfer_status(
    registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    session_id: String,
    transfer_id: String,
) -> Result<SftpTransferResponse, String> {
    crate::commands::sftp::sftp_transfer_status(registry.inner(), session_id, transfer_id)
}

// ===== terminal =====
#[tauri::command(rename_all = "snake_case")]
pub fn terminal_shell_options(
) -> TerminalShellOptionsResponse {
    crate::commands::terminal::terminal_shell_options()
}

#[tauri::command(rename_all = "snake_case")]
pub fn terminal_list(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    project_path_key: Option<String>,
) -> TerminalListResponse {
    crate::commands::terminal::terminal_list(registry.inner(), project_path_key)
}

#[tauri::command(rename_all = "snake_case")]
pub fn terminal_create(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    cwd: String,
    project_path_key: Option<String>,
    shell: Option<String>,
    title: Option<String>,
    cols: Option<u16>,
    rows: Option<u16>,
) -> Result<TerminalSnapshotResponse, String> {
    crate::commands::terminal::terminal_create(registry.inner(), cwd, project_path_key, shell, title, cols, rows)
}

#[tauri::command(rename_all = "snake_case")]
pub async fn terminal_create_ssh(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    cwd: String,
    project_path_key: Option<String>,
    ssh_host_id: String,
    title: Option<String>,
    cols: Option<u16>,
    rows: Option<u16>,
    sftp_enabled: Option<bool>,
) -> Result<TerminalSshCreateResponse, String> {
    crate::commands::terminal::terminal_create_ssh(registry.inner(), cwd, project_path_key, ssh_host_id, title, cols, rows, sftp_enabled).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn terminal_answer_ssh_prompt(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    prompt_id: String,
    prompt_answer: Option<String>,
    trust_host_key: Option<bool>,
) -> Result<TerminalSshCreateResponse, String> {
    crate::commands::terminal::terminal_answer_ssh_prompt(registry.inner(), prompt_id, prompt_answer, trust_host_key).await
}

#[tauri::command(rename_all = "snake_case")]
pub fn terminal_cancel_ssh_prompt(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    prompt_id: String,
) -> Result<(), String> {
    crate::commands::terminal::terminal_cancel_ssh_prompt(registry.inner(), prompt_id)
}

#[tauri::command(rename_all = "snake_case")]
pub async fn terminal_ssh_reconnect(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    session_id: String,
) -> Result<TerminalSessionRecord, String> {
    crate::commands::terminal::terminal_ssh_reconnect(registry.inner(), session_id).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn terminal_ssh_latency(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    session_id: String,
) -> Result<TerminalSshLatencyResponse, String> {
    crate::commands::terminal::terminal_ssh_latency(registry.inner(), session_id).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn terminal_ssh_exec(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    run_registry: tauri::State<'_, Arc<ShellRunRegistry>>,
    session_id: String,
    command: String,
    cwd: Option<String>,
    timeout_ms: Option<u64>,
    max_bytes: Option<usize>,
    run_id: Option<String>,
) -> Result<TerminalSshExecResponse, String> {
    crate::commands::terminal::terminal_ssh_exec(registry.inner(), run_registry.inner(), session_id, command, cwd, timeout_ms, max_bytes, run_id).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn terminal_ssh_local_forward_start(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    session_id: String,
    project_path_key: Option<String>,
    remote_host: String,
    remote_port: u32,
    local_port: Option<u32>,
) -> Result<SshLocalForwardActionResponse, String> {
    crate::commands::terminal::terminal_ssh_local_forward_start(registry.inner(), session_id, project_path_key, remote_host, remote_port, local_port).await
}

#[tauri::command(rename_all = "snake_case")]
pub fn terminal_ssh_local_forward_list(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    session_id: Option<String>,
    project_path_key: Option<String>,
) -> Result<SshLocalForwardListResponse, String> {
    crate::commands::terminal::terminal_ssh_local_forward_list(registry.inner(), session_id, project_path_key)
}

#[tauri::command(rename_all = "snake_case")]
pub async fn terminal_ssh_local_forward_stop(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    forward_id: String,
    session_id: Option<String>,
) -> Result<SshLocalForwardActionResponse, String> {
    crate::commands::terminal::terminal_ssh_local_forward_stop(registry.inner(), forward_id, session_id).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn terminal_ssh_local_forward_check_port(
    local_port: u32,
) -> Result<bool, String> {
    crate::commands::terminal::terminal_ssh_local_forward_check_port(local_port).await
}

#[tauri::command(rename_all = "snake_case")]
pub fn ssh_terminal_tabs_list(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    project_path_key: String,
) -> Result<SshTerminalTabsSnapshot, String> {
    crate::commands::terminal::ssh_terminal_tabs_list(registry.inner(), project_path_key)
}

#[tauri::command(rename_all = "snake_case")]
pub fn ssh_terminal_tab_open(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    session_id: String,
    kind: String,
) -> Result<SshTerminalTabsSnapshot, String> {
    crate::commands::terminal::ssh_terminal_tab_open(registry.inner(), session_id, kind)
}

#[tauri::command(rename_all = "snake_case")]
pub fn ssh_terminal_tab_close(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    tab_id: String,
) -> Result<SshTerminalTabsSnapshot, String> {
    crate::commands::terminal::ssh_terminal_tab_close(registry.inner(), tab_id)
}

#[tauri::command(rename_all = "snake_case")]
pub fn terminal_stream_attach(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    session_id: String,
    max_bytes: Option<usize>,
) -> Result<TerminalStreamSnapshotResponse, String> {
    crate::commands::terminal::terminal_stream_attach(registry.inner(), session_id, max_bytes)
}

#[tauri::command(rename_all = "snake_case")]
pub fn terminal_stream_input(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    session_id: String,
    bytes: Vec<u8>,
) -> Result<(), String> {
    crate::commands::terminal::terminal_stream_input(registry.inner(), session_id, bytes)
}

#[tauri::command(rename_all = "snake_case")]
pub fn terminal_stream_resize(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    session_id: String,
    cols: u16,
    rows: u16,
) -> Result<(), String> {
    crate::commands::terminal::terminal_stream_resize(registry.inner(), session_id, cols, rows)
}

#[tauri::command(rename_all = "snake_case")]
pub fn terminal_rename(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    session_id: String,
    title: String,
) -> Result<TerminalSessionRecord, String> {
    crate::commands::terminal::terminal_rename(registry.inner(), session_id, title)
}

#[tauri::command(rename_all = "snake_case")]
pub fn terminal_close(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    sftp_registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    session_id: String,
) -> Result<TerminalSessionRecord, String> {
    crate::commands::terminal::terminal_close(registry.inner(), sftp_registry.inner(), session_id)
}

#[tauri::command(rename_all = "snake_case")]
pub fn terminal_close_project(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    sftp_registry: tauri::State<'_, Arc<SftpSessionRegistry>>,
    project_path_key: String,
) -> Result<TerminalListResponse, String> {
    crate::commands::terminal::terminal_close_project(registry.inner(), sftp_registry.inner(), project_path_key)
}

#[tauri::command(rename_all = "snake_case")]
pub fn terminal_read_tail(
    registry: tauri::State<'_, Arc<TerminalSessionRegistry>>,
    project_path_key: String,
    session_id: Option<String>,
    max_bytes: Option<usize>,
) -> Result<TerminalReadTailResponse, String> {
    crate::commands::terminal::terminal_read_tail(registry.inner(), project_path_key, session_id, max_bytes)
}

// ===== shell =====
#[tauri::command(rename_all = "snake_case")]
pub async fn shell_run(
    registry: tauri::State<'_, Arc<ShellRunRegistry>>,
    workdir: String,
    command: String,
    cwd: Option<String>,
    timeout_ms: Option<u64>,
    max_timeout_ms: Option<u64>,
    provider_id: Option<String>,
    run_id: Option<String>,
) -> Result<ShellRunResponse, String> {
    crate::commands::shell::shell_run(registry.inner(), workdir, command, cwd, timeout_ms, max_timeout_ms, provider_id, run_id).await
}

#[tauri::command(rename_all = "snake_case")]
pub fn runtime_cancel(
    registry: tauri::State<'_, Arc<ShellRunRegistry>>,
    run_id: String,
) -> ShellCancelResponse {
    crate::commands::shell::runtime_cancel(registry.inner(), run_id)
}

// ===== chat_file_links =====
#[tauri::command(rename_all = "snake_case")]
pub async fn open_chat_file_link(
    conversation_id: String,
    workdir: String,
    path: String,
    source: String,
    line: Option<u32>,
    end_line: Option<u32>,
    column: Option<u32>,
    open_in_file_manager: Option<bool>,
) -> Result<ChatFileLinkOpenResponse, ChatFileLinkError> {
    crate::commands::chat_file_links::open_chat_file_link(conversation_id, workdir, path, source, line, end_line, column, open_in_file_manager).await
}

// ===== fs =====
#[tauri::command]
pub async fn fs_read_image_source(
    workdir: String,
    source: String,
    source_type: Option<String>,
    mime_type: Option<String>,
) -> Result<ReadResponse, FsCommandError> {
    crate::commands::fs::fs_read_image_source(workdir, source, source_type, mime_type).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_read_workspace_image(
    workdir: String,
    path: String,
) -> Result<ReadResponse, FsCommandError> {
    crate::commands::fs::fs_read_workspace_image(workdir, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_read_text(
    workdir: String,
    path: String,
    start_line: Option<usize>,
    limit: Option<usize>,
    page_start: Option<usize>,
    page_limit: Option<usize>,
    cell_start: Option<usize>,
    cell_limit: Option<usize>,
) -> Result<ReadResponse, FsCommandError> {
    crate::commands::fs::fs_read_text(workdir, path, start_line, limit, page_start, page_limit, cell_start, cell_limit).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_read_editable_text(
    workdir: String,
    path: String,
) -> Result<ReadEditableTextResponse, FsCommandError> {
    crate::commands::fs::fs_read_editable_text(workdir, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_path_status(
    workdir: String,
    path: String,
) -> Result<PathStatusResponse, FsCommandError> {
    crate::commands::fs::fs_path_status(workdir, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_write_text(
    workdir: String,
    path: String,
    content: String,
    mode: String,
    expected_mtime_ms: Option<u64>,
    expected_content_hash: Option<String>,
) -> Result<WriteTextResponse, FsCommandError> {
    crate::commands::fs::fs_write_text(workdir, path, content, mode, expected_mtime_ms, expected_content_hash).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_edit_text(
    workdir: String,
    path: String,
    old_string: String,
    new_string: String,
    expected_replacements: Option<usize>,
    replace_all: Option<bool>,
    expected_mtime_ms: Option<u64>,
    expected_content_hash: Option<String>,
) -> Result<EditTextResponse, FsCommandError> {
    crate::commands::fs::fs_edit_text(workdir, path, old_string, new_string, expected_replacements, replace_all, expected_mtime_ms, expected_content_hash).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_delete(
    workdir: String,
    path: String,
) -> Result<DeleteResponse, FsCommandError> {
    crate::commands::fs::fs_delete(workdir, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_open_workspace_path(
    workdir: String,
    path: String,
    mode: Option<String>,
) -> Result<OpenWorkspacePathResponse, FsCommandError> {
    crate::commands::fs::fs_open_workspace_path(workdir, path, mode).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_create_dir(
    workdir: String,
    path: String,
) -> Result<CreateDirResponse, FsCommandError> {
    crate::commands::fs::fs_create_dir(workdir, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_rename(
    workdir: String,
    from_path: String,
    to_path: String,
) -> Result<RenameResponse, FsCommandError> {
    crate::commands::fs::fs_rename(workdir, from_path, to_path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_roots(
) -> Result<FsRootsResponse, String> {
    crate::commands::fs::fs_roots().await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_list_dirs(
    path: String,
    max_results: Option<usize>,
) -> Result<FsListDirsResponse, String> {
    crate::commands::fs::fs_list_dirs(path, max_results).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_list(
    workdir: String,
    path: Option<String>,
    depth: Option<usize>,
    offset: Option<usize>,
    max_results: Option<usize>,
    show_hidden: Option<bool>,
) -> Result<ListResponse, FsCommandError> {
    crate::commands::fs::fs_list(workdir, path, depth, offset, max_results, show_hidden).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_glob(
    workdir: String,
    path: Option<String>,
    pattern: String,
    offset: Option<usize>,
    max_results: Option<usize>,
    sort_by: Option<String>,
) -> Result<GlobResponse, FsCommandError> {
    crate::commands::fs::fs_glob(workdir, path, pattern, offset, max_results, sort_by).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_grep(
    workdir: String,
    path: Option<String>,
    pattern: String,
    file_pattern: Option<String>,
    ignore_case: Option<bool>,
    output_mode: Option<String>,
    head_limit: Option<usize>,
    offset: Option<usize>,
    context: Option<usize>,
    multiline: Option<bool>,
) -> Result<GrepResponse, FsCommandError> {
    crate::commands::fs::fs_grep(workdir, path, pattern, file_pattern, ignore_case, output_mode, head_limit, offset, context, multiline).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn fs_mention_list(
    workdir: String,
    max_results: Option<usize>,
    query: Option<String>,
    show_hidden: Option<bool>,
) -> Result<MentionListResponse, String> {
    crate::commands::fs::fs_mention_list(workdir, max_results, query, show_hidden).await
}

// ===== git =====
#[tauri::command(rename_all = "snake_case")]
pub async fn git_status(
    workdir: String,
) -> Result<GitRepositoryState, String> {
    crate::commands::git::git_status(workdir).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_discover_repositories(
    workdir: String,
) -> Result<GitRepositoryDiscovery, String> {
    crate::commands::git::git_discover_repositories(workdir).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_branches(
    workdir: String,
) -> Result<GitBranchesResponse, String> {
    crate::commands::git::git_branches(workdir).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_switch_branch(
    workdir: String,
    branch: String,
    kind: Option<String>,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_switch_branch(workdir, branch, kind).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_create_branch(
    workdir: String,
    branch: String,
    start_point: Option<String>,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_create_branch(workdir, branch, start_point).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_init(
    workdir: String,
    branch: Option<String>,
    user_name: Option<String>,
    user_email: Option<String>,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_init(workdir, branch, user_name, user_email).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_clone_repository(
    parent: String,
    name: String,
    remote_url: String,
    branch: Option<String>,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_clone_repository(parent, name, remote_url, branch).await
}

#[tauri::command(rename_all = "snake_case")]
pub fn git_clone_repository_start(
    registry: tauri::State<'_, Arc<GitCloneTaskRegistry>>,
    parent: String,
    name: String,
    remote_url: String,
    branch: Option<String>,
) -> Result<GitCloneTask, String> {
    crate::commands::git::git_clone_repository_start(registry.inner(), parent, name, remote_url, branch)
}

#[tauri::command]
pub fn git_clone_repository_tasks(
    registry: tauri::State<'_, Arc<GitCloneTaskRegistry>>,
) -> Result<Vec<GitCloneTask>, String> {
    crate::commands::git::git_clone_repository_tasks(registry.inner())
}

#[tauri::command(rename_all = "snake_case")]
pub fn git_clone_repository_cancel(
    registry: tauri::State<'_, Arc<GitCloneTaskRegistry>>,
    task_id: String,
) -> Result<GitCloneTask, String> {
    crate::commands::git::git_clone_repository_cancel(registry.inner(), task_id)
}

#[tauri::command(rename_all = "snake_case")]
pub fn git_clone_repository_dismiss(
    registry: tauri::State<'_, Arc<GitCloneTaskRegistry>>,
    task_id: String,
) -> Result<Vec<GitCloneTask>, String> {
    crate::commands::git::git_clone_repository_dismiss(registry.inner(), task_id)
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_list_remote_branches(
    remote_url: String,
) -> Result<GitRemoteBranchesResponse, String> {
    crate::commands::git::git_list_remote_branches(remote_url).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_diff(
    workdir: String,
    mode: Option<String>,
    path: Option<String>,
) -> Result<GitDiffResponse, String> {
    crate::commands::git::git_diff(workdir, mode, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_log(
    workdir: String,
    limit: Option<usize>,
    skip: Option<usize>,
) -> Result<GitLogResponse, String> {
    crate::commands::git::git_log(workdir, limit, skip).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_commit_details(
    workdir: String,
    commit: String,
) -> Result<GitCommitDetailsResponse, String> {
    crate::commands::git::git_commit_details(workdir, commit).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_compare_commit_with_remote(
    workdir: String,
    commit: String,
) -> Result<GitDiffResponse, String> {
    crate::commands::git::git_compare_commit_with_remote(workdir, commit).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_commit_diff(
    workdir: String,
    commit: String,
    path: Option<String>,
) -> Result<GitDiffResponse, String> {
    crate::commands::git::git_commit_diff(workdir, commit, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_stage(
    workdir: String,
    path: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_stage(workdir, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_stage_all(
    workdir: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_stage_all(workdir).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_unstage(
    workdir: String,
    path: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_unstage(workdir, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_unstage_all(
    workdir: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_unstage_all(workdir).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_discard(
    workdir: String,
    path: String,
    old_path: Option<String>,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_discard(workdir, path, old_path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_discard_all(
    workdir: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_discard_all(workdir).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_add_to_gitignore(
    workdir: String,
    path: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_add_to_gitignore(workdir, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_open_system_file_location(
    workdir: String,
    path: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_open_system_file_location(workdir, path).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_commit(
    workdir: String,
    message: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_commit(workdir, message).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_fetch(
    workdir: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_fetch(workdir).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_pull(
    workdir: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_pull(workdir).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_set_remote(
    workdir: String,
    remote_url: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_set_remote(workdir, remote_url).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_push(
    workdir: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_push(workdir).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_delete_branch(
    workdir: String,
    branch: String,
    force: Option<bool>,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_delete_branch(workdir, branch, force).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_rename_branch(
    workdir: String,
    branch: String,
    new_branch: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_rename_branch(workdir, branch, new_branch).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_stash_push(
    workdir: String,
    message: Option<String>,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_stash_push(workdir, message).await
}

#[tauri::command(rename_all = "snake_case")]
pub async fn git_stash_pop(
    workdir: String,
) -> Result<GitOperationResponse, String> {
    crate::commands::git::git_stash_pop(workdir).await
}

// ===== subagent_worktree =====
#[tauri::command]
pub async fn subagent_worktree_create(
    input: SubagentWorktreeCreateInput,
) -> Result<SubagentWorktreeCreateResponse, String> {
    crate::commands::subagent_worktree::subagent_worktree_create(input).await
}

#[tauri::command]
pub async fn subagent_worktree_status(
    input: SubagentWorktreeStatusInput,
) -> Result<SubagentWorktreeStatusResponse, String> {
    crate::commands::subagent_worktree::subagent_worktree_status(input).await
}

#[tauri::command]
pub async fn subagent_worktree_apply(
    input: SubagentWorktreeApplyInput,
) -> Result<SubagentWorktreeApplyResponse, String> {
    crate::commands::subagent_worktree::subagent_worktree_apply(input).await
}

#[tauri::command]
pub async fn subagent_worktree_cleanup(
    input: SubagentWorktreeCleanupInput,
) -> Result<SubagentWorktreeCleanupItem, String> {
    crate::commands::subagent_worktree::subagent_worktree_cleanup(input).await
}

// ===== proxy =====
#[tauri::command]
pub fn proxy_get_server_info(
    state: tauri::State<'_, Arc<ProxyServerState>>,
) -> ProxyServerInfo {
    crate::services::proxy::proxy_get_server_info(state.inner())
}
